apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.image.name }}
    app.kubernetes.io/part-of: {{ .Values.image.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.portHttps }}
      targetPort: {{ .Values.service.targetPortHttps }}
      name: {{ .Values.service.https }}
  selector:
    app.kubernetes.io/name: {{ .Values.image.name }}
    app.kubernetes.io/part-of: {{ .Values.image.name }}