Name: kw-system
Host: 0.0.0.0
Port: 8001
Mode: test
Timeout: 5000
Middlewares:
  Log: true

RedisDb:
  Addrs:
    - 127.0.0.1:6379
  Pass: kwever123!QWE
  DB: 0
  Username: ""
  MasterName: e
  MaxRetries: 3
DataSources:
  Host: 127.0.0.1
  Port: 3306
  Config: ""
  DBName: kweaver
  Username: root
  Password: kwever123!QWE
  DriverName: mysql #mysql|sqlserver|dm8|mariadb|tidb