responses:
  '200':
    description: 'operation success'
    schema:
      $ref: '#/definitions/BuilderRes'
  '500':
    description: 'operation failure'
    schema:
      $ref: '#/definitions/NewBuilderErrResponse'
  '400':
    description: 'parameter error'
    schema:
      $ref: '#/definitions/NewBuilderErrResponse'