basePath: /api
host: https://{host}:{port}
info:
  description: 欢迎使用KWeaver OpenAPI
  title: KWeaver OpenAPI
  version: 0.1.0
schemes:
- https
swagger: '2.0'
tags:
- description: 知识网络生成服务 Knowledge Network Builder（KN Builder）：利用人工智能技术，将不同形态的数据转化为知识网络，实现数据知识化。包括知识图谱、语言模型和规则库。
  name: KN Builder
