mariadb:
  host: 10.4.106.255
  port: 3306
  user: "anydata"
  password: "Qwe123!@#"
  database: "anydata"
mongodb:
  host: 10.4.106.255
  port: 28000
  user: "root"
  password: "eisoo.com123"
  database: "anydata"
redis:
  mode: sentinel
  master_name: mymaster
  sentinel:
    - host: 10.4.69.47
      port: 26379
    - host: 10.4.69.47
      port: 26380
    - host: 10.4.69.47
      port: 26381
  sentinel_account: ~
  sentinel_password: ~
  redis_account: ~
  redis_password: "123456"



