tmysql:
  read_write:
      host: 10.4.70.120
      port: 3306
      user: root
      password: NewPass123!
      maxconnections: 3
      mincached: 2
      maxcached: 5
      maxshared: 5
      blocking: True
      setsession: []
      ping: 1
      database: anydata
      charset: utf8
#  read_write_ceshi:
#      host: 10.4.69.177
#      port: 13306
#      user: root
#      password: eisoo.com123
#      maxconnections: 3
#      mincached: 2
#      maxcached: 5
#      maxshared: 5
#      blocking: True
#      setsession: []
#      ping: 1
#      database: anydata
#      charset: utf8
  read_write_ceshi:
      host: 10.2.174.230
      port: 3320
      user: root
      password: eisoo.com
      maxconnections: 3
      mincached: 2
      maxcached: 5
      maxshared: 5
      blocking: True
      setsession: []
      ping: 1
      database: anydata
      charset: utf8
  ###10.4.71.138
  ####10.2.174.243
  #####10.2.235.235--20
  #######10.2.174.230
  read_write1:
      host: 10.2.235.235
      port: 3320
      user: admin
      password: Qwe123!@#
      maxconnections: 3
      mincached: 2
      maxcached: 5
      maxshared: 5
      blocking: True
      setsession: []
      ping: 1
      database: anydata
      charset: utf8
  docker_db:
      host: rds-proton-rds-mariadb-cluster
#      host: 10.2.196.57
      port: 3320
      user: admin
      password: Qwe123!@#
      maxconnections: 3
      mincached: 2
      maxcached: 5
      maxshared: 5
      blocking: True
      setsession: []
      ping: 1
      database: anydata
      charset: utf8
