mariadb:
  host: kw-mariadb
  port: 3306
  user: root
  password: KWeaver
  database: anydata
mongodb:
  host: kw-mongodb
  port: 27017
  user: root
  password: KWeaver
  database: anydata
redis:
  mode: stand-alone
  host: kw-redis
  port: 6379
  user: ~
  password: KWeaver
