const CHANGE_ANY_DATA_LANG = 'src_change_kwLang';

const KNOWLEDGE_GRAPH_CHANGE_STATUS = 'KNOWLEDGE_GRAPH_CHANGE_STATUS';

const SQL_SEARCH_HISTORY = 'SQL_SEARCH_HISTORY';

const UPLOAD_CHANGE_VISIBLE = 'upload_change_visible';
const UPLOAD_CHANGE_FILE = 'upload_change_file';
const UPLOAD_CHANGE_STATUS = 'upload_change_status';

const GRAPH_QA = 'knowledge/graphqa';

export {
  CHANGE_ANY_DATA_LANG,
  KNOWLEDGE_GRAPH_CHANGE_STATUS,
  SQL_SEARCH_HISTORY,
  UPLOAD_CHANGE_VISIBLE,
  UPLOAD_CHANGE_FILE,
  UPLOAD_CHANGE_STATUS,
  GRAPH_QA
};
