import React from 'react';
import { shallow } from 'enzyme';
import InfoContent from './index';

it('renders without crashing', () => {
  shallow(<InfoContent />);
});

describe('function test', () => {
  const wrapper = shallow(<InfoContent />);
  const instance = wrapper.instance();

  wrapper.setProps({
    bottomLines: [
      {
        beforeWord: 406,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 30,
        entity: 'label',
        lineIndex: 1,
        property: 'name',
        selectedIndex: 0,
        startIndex: 29,
        tagWidth: 28,
        text: '电子',
        uniqueMark: 0
      },
      {
        beforeWord: 980,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 72,
        entity: 'label',
        lineIndex: 1,
        property: 'name',
        selectedIndex: 0,
        startIndex: 70,
        tagWidth: 42,
        text: '电现象',
        uniqueMark: 1
      },
      {
        beforeWord: 37,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 5,
        entity: 'label',
        lineIndex: 6,
        property: 'name',
        selectedIndex: 0,
        startIndex: 4,
        tagWidth: 28,
        text: '发现',
        uniqueMark: 2
      },
      {
        beforeWord: 28,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 3,
        entity: 'label',
        lineIndex: 14,
        property: 'name',
        selectedIndex: 0,
        startIndex: 2,
        tagWidth: 28,
        text: '发现',
        uniqueMark: 3
      },
      {
        beforeWord: 168,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 14,
        entity: 'label',
        lineIndex: 15,
        property: 'name',
        selectedIndex: 0,
        startIndex: 12,
        tagWidth: 42,
        text: '电现象',
        uniqueMark: 4
      },
      {
        beforeWord: 168,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 14,
        entity: 'label',
        lineIndex: 16,
        property: 'name',
        selectedIndex: 0,
        startIndex: 12,
        tagWidth: 42,
        text: '电现象',
        uniqueMark: 5
      },
      {
        beforeWord: 341,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 27,
        entity: 'label',
        lineIndex: 25,
        property: 'name',
        selectedIndex: 0,
        startIndex: 25,
        tagWidth: 42,
        text: '电现象',
        uniqueMark: 6
      },
      {
        beforeWord: 218,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 19,
        entity: 'label',
        lineIndex: 30,
        property: 'name',
        selectedIndex: 0,
        startIndex: 18,
        tagWidth: 28,
        text: '发现',
        uniqueMark: 7
      },
      {
        beforeWord: 2536,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 187,
        entity: 'label',
        lineIndex: 31,
        property: 'name',
        selectedIndex: 0,
        startIndex: 186,
        tagWidth: 28,
        text: '电流',
        uniqueMark: 8
      },
      {
        beforeWord: 148,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 14,
        entity: 'label',
        lineIndex: 31,
        property: 'name',
        selectedIndex: 0,
        startIndex: 13,
        tagWidth: 28,
        text: '发现',
        uniqueMark: 9
      },
      {
        beforeWord: 274,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 26,
        entity: 'label',
        lineIndex: 31,
        property: 'name',
        selectedIndex: 0,
        startIndex: 22,
        tagWidth: 70,
        text: '静电发电机',
        uniqueMark: 10
      },
      {
        beforeWord: 302,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 25,
        entity: 'label',
        lineIndex: 35,
        property: 'name',
        selectedIndex: 0,
        startIndex: 24,
        tagWidth: 28,
        text: '电流',
        uniqueMark: 11
      },
      {
        beforeWord: 260,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 22,
        entity: 'label',
        lineIndex: 35,
        property: 'name',
        selectedIndex: 0,
        startIndex: 21,
        tagWidth: 28,
        text: '发现',
        uniqueMark: 12
      },
      {
        beforeWord: 278,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 24,
        entity: 'label',
        lineIndex: 36,
        property: 'name',
        selectedIndex: 0,
        startIndex: 23,
        tagWidth: 28,
        text: '发现',
        uniqueMark: 13
      },
      {
        beforeWord: 1710,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 128,
        entity: 'label',
        lineIndex: 37,
        property: 'name',
        selectedIndex: 0,
        startIndex: 127,
        tagWidth: 28,
        text: '电子',
        uniqueMark: 14
      },
      {
        beforeWord: 638,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 49,
        entity: 'label',
        lineIndex: 37,
        property: 'name',
        selectedIndex: 0,
        startIndex: 48,
        tagWidth: 28,
        text: '发现',
        uniqueMark: 15
      },
      {
        beforeWord: 1582,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 116,
        entity: 'label',
        lineIndex: 38,
        property: 'name',
        selectedIndex: 0,
        startIndex: 115,
        tagWidth: 28,
        text: '发现',
        uniqueMark: 16
      },
      {
        beforeWord: 2839,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 210,
        entity: 'label',
        lineIndex: 42,
        property: 'name',
        selectedIndex: 0,
        startIndex: 209,
        tagWidth: 28,
        text: '电子',
        uniqueMark: 17
      },
      {
        beforeWord: 232,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 20,
        entity: 'label',
        lineIndex: 42,
        property: 'name',
        selectedIndex: 0,
        startIndex: 19,
        tagWidth: 28,
        text: '发现',
        uniqueMark: 18
      },
      {
        beforeWord: 940,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 73,
        entity: 'label',
        lineIndex: 43,
        property: 'name',
        selectedIndex: 0,
        startIndex: 72,
        tagWidth: 28,
        text: '电子',
        uniqueMark: 19
      },
      {
        beforeWord: 0,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 1,
        entity: 'label',
        lineIndex: 45,
        property: 'name',
        selectedIndex: 0,
        startIndex: 0,
        tagWidth: 28,
        text: '电子',
        uniqueMark: 20
      },
      {
        beforeWord: 838,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 72,
        entity: 'label',
        lineIndex: 46,
        property: 'name',
        selectedIndex: 0,
        startIndex: 71,
        tagWidth: 28,
        text: '电子',
        uniqueMark: 21
      },
      {
        beforeWord: 376,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 39,
        entity: 'label',
        lineIndex: 46,
        property: 'name',
        selectedIndex: 0,
        startIndex: 38,
        tagWidth: 28,
        text: '电流',
        uniqueMark: 22
      },
      {
        beforeWord: 227,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 21,
        entity: 'label',
        lineIndex: 47,
        property: 'name',
        selectedIndex: 0,
        startIndex: 20,
        tagWidth: 28,
        text: '电子',
        uniqueMark: 23
      },
      {
        beforeWord: 0,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 1,
        entity: 'label',
        lineIndex: 48,
        property: 'name',
        selectedIndex: 0,
        startIndex: 0,
        tagWidth: 28,
        text: '电流',
        uniqueMark: 24
      },
      {
        beforeWord: 161,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 21,
        entity: 'label',
        lineIndex: 49,
        property: 'name',
        selectedIndex: 0,
        startIndex: 20,
        tagWidth: 28,
        text: '电子',
        uniqueMark: 25
      },
      {
        beforeWord: 623,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 54,
        entity: 'label',
        lineIndex: 49,
        property: 'name',
        selectedIndex: 0,
        startIndex: 53,
        tagWidth: 28,
        text: '电流',
        uniqueMark: 26
      },
      {
        beforeWord: 252,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 30,
        entity: 'label',
        lineIndex: 50,
        property: 'name',
        selectedIndex: 0,
        startIndex: 29,
        tagWidth: 28,
        text: '电流',
        uniqueMark: 27
      },
      {
        beforeWord: 223,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 21,
        entity: 'label',
        lineIndex: 51,
        property: 'name',
        selectedIndex: 0,
        startIndex: 20,
        tagWidth: 28,
        text: '电流',
        uniqueMark: 28
      },
      {
        beforeWord: 0,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 1,
        entity: 'label',
        lineIndex: 58,
        property: 'name',
        selectedIndex: 0,
        startIndex: 0,
        tagWidth: 28,
        text: '电流',
        uniqueMark: 29
      },
      {
        beforeWord: 904,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 83,
        entity: 'label',
        lineIndex: 60,
        property: 'name',
        selectedIndex: 0,
        startIndex: 82,
        tagWidth: 28,
        text: '电子',
        uniqueMark: 30
      },
      {
        beforeWord: 415,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 46,
        entity: 'label',
        lineIndex: 60,
        property: 'name',
        selectedIndex: 0,
        startIndex: 45,
        tagWidth: 28,
        text: '电流',
        uniqueMark: 31
      },
      {
        beforeWord: 173,
        color: '#D8707A',
        desWord: 'label：name',
        endIndex: 18,
        entity: 'label',
        lineIndex: 61,
        property: 'name',
        selectedIndex: 0,
        startIndex: 17,
        tagWidth: 28,
        text: '电流',
        uniqueMark: 32
      }
    ]
  });

  expect(instance.initData()).toBe();
});
