kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.image.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
#  storageClassName: nfs
  selector:
    matchLabels:
      pv: {{ .Values.image.name }}