version: '3.7'

services:
  kw-nginx:
    container_name: kw-nginx
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log/error.log:/var/log/nginx/error.log
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai
    networks:
      - kw-network
    depends_on:
      - kw-studio
      - kw-builder

  kw-studio:
    container_name: kw-studio
    image: acr.aishu.cn/ad/kw-studio
    restart: always
    volumes:
      - ./kwconfig/:/etc/studio/:ro
    networks:
      - kw-network
    ports:
      - '6800:6800'
    environment:
      - TZ=Asia/Shanghai
    expose:
      - '6800'

  kw-builder:
    container_name: kw-builder
    image: acr.aishu.cn/ad/kw-builder
    restart: always
    volumes:
      - ./kwconfig/:/etc/builder/:ro
    networks:
      - kw-network
    ports:
      - '6475:6475'
    environment:
      - TZ=Asia/Shanghai
    expose:
      - '6475'
      - '6485'
      - '6488'
    depends_on:
      - kw-studio

  kw-algserver:
    container_name: kw-algserver
    image: acr.aishu.cn/ad/kw-algserver
    restart: always
    volumes:
      - ./kwconfig/:/etc/builder/:ro
    networks:
      - kw-network
    ports:
      - '8080:8080'
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - kw-mariadb

  kw-engine:
    container_name: kw-engine
    image: acr.aishu.cn/ad/kw-engine
    restart: always
    volumes:
      - ./kwconfig/:/etc/builder/:ro
    networks:
      - kw-network
    ports:
      - '6474:6474'
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - kw-mariadb
      - kw-builder
        
networks:
  kw-network:
    driver: bridge

volumes:
  db_data: