apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: {{ .Values.image.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
    spec:
      containers: 
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.ports.name1 }}
              containerPort: {{ .Values.service.ports.port1 }}
            - name: {{ .Values.service.ports.name2 }}
              containerPort: {{ .Values.service.ports.port2 }}
            - name: {{ .Values.service.ports.name3 }}
              containerPort: {{ .Values.service.ports.port3 }}
          volumeMounts:
            - mountPath: /etc/builder/
              name: conf
              readOnly: true
            - name: host-time
              mountPath: /etc/localtime
      hostAliases:
      - ip: {{ .Values.hostAliases.ip }}
        hostnames:
        - {{ .Values.hostAliases.hostnames }}
      volumes:
        - name: conf
          hostPath:
            path: {{ .Values.volumes.hostPath }}
        - name: host-time
          hostPath:
            path: /etc/localtime