apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.ports.name1 }}
      port: {{ .Values.service.ports.port1 }}
      targetPort: {{ .Values.service.ports.targetPort1 }}
      protocol: TCP
    - name: {{ .Values.service.ports.name2 }}
      port: {{ .Values.service.ports.port2 }}
      targetPort: {{ .Values.service.ports.targetPort2 }}
      protocol: TCP
    - name: {{ .Values.service.ports.name3 }}
      port: {{ .Values.service.ports.port3 }}
      targetPort: {{ .Values.service.ports.targetPort3 }}
      protocol: TCP
  selector:
    app: {{ .Values.image.name }}