server:
  host: 0.0.0.0
  port: 6800
  mode: release

mariadb:
  user: root
  password: 123456
  port: 3306
  host: localhost
  database: anydata
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-lifetime: 60 #60min
  log-mode: false
  log-level: 4

redis:
  mode: stand-alone #stand-alone sentinel
  host: 10.4.68.144
  port: 6379
  user: ~
  password: "123456"
  master_name: mymaster
  sentinel:
    - host: 10.4.69.47
      port: 26380
    - host: 10.4.69.47
      port: 26381
  sentinel_user: ~
  sentinel_password: ~
  db: 0

#zap配置
zap:
  level: 'info'
  format: 'console' #console json
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true
  prefix: '[github.com/KWeaver/kw-studio]'
