server:
  host: 0.0.0.0
  port: 6800
  mode: release

mariadb:
  user: root
  password: 123456
  port: 3306
  host: localhost
  database: anydata
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-lifetime: 60 #60min
  log-mode: false
  log-level: 4

redis:
  mode: stand-alone #stand-alone sentinel
  host: 10.4.68.144
  port: 6379
  user: ""
  password: ""
  master_name: master
  sentinel:
    - host: 10.4.68.144
      port: 6379
  sentinel_user: ""
  sentinel_password: Qwe123!@#
  db: 0

#zap配置
zap:
  level: 'info'
  format: 'console' #console json
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true
  prefix: '[github.com/KWeaver/kw-studio]'

swagger:
  title: "KWeaver OpenAPI"
  version: "1.0.0"
  description: "欢迎使用KWeaver 1.0.0 OpenAPI"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  tags:
    - {"name": "Introduction", "description": "KWeaver提供OpenAPI能力，通过调用KWeaver的OpenAPI使用KWeaver的各项功能，实现应用和KWeaver的集成和交互操作。"}
    - {"name": "Studio", "description": "KWeaver管理界面" }
    - {"name": "KN Builder", "description": "知识网络生成服务 Knowledge Network Builder（KN Builder）：利用人工智能技术，将不同形态的数据转化为知识网络，实现数据知识化。包括知识图谱、语言模型和规则库。"}
    - {"name": "CEngine", "description": "知识网络探索式分析相关API，可实现实体的搜索，以及探索与其相关联的实体。遵循GraphQL接口规范，详细schema可查看graphql schema"}
  doc_urls:
    - "http://localhost:6800/swagger/doc.json"
    - "http://kw-builder:6475/swagger/swagger.json"
    - "http://kw-engine:6474/swagger/doc.json"