responses:
  '200':
    description: '操作成功'
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/builder.BuilderRes'
  '500':
    description: '服务器异常'
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/builder.BuilderRes'
  '400':
    description: '参数错误'
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/builder.OldBuilderErrResponse'
parameters:
  - in: header
    name: appid
    description: AnyDATA账户的唯一标识，可通过/rbac/v1/user/appId获取
    required: true
    schema:
      type: string
  - in: header
    name: timestamp
    description: 此时间戳的接受范围以AD的系统时间为基准，接受客户端的时间在AD的系统有限期为30分钟，误差时间为15分钟
    required: false
    schema:
      type: string
  - in: header
    name: appkey
    description: 客户端使用特定的算法通过appid、时间戳和请求参数这三个参数生成的校验字符串，用于后端校验请求的合法性
    required: false
    schema:
      type: string
