replicaCount: 1

namespace: kweaver

image:
  registry: acr.aishu.cn
  repository: /ad/kw-algserver
  tag: latest
  pullPolicy: IfNotPresent
  name: kw-algserver

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  
volumes:  
  hostPath: /kweaver/deploy/kw-k8s/conf/kwconfig/