// Code generated by MockGen. DO NOT EDIT.
// Source: ../condition/condition.go

// Package mock_condition is a generated GoMock package.
package mock_condition

import (
	context "context"
	condition "ontology-manager/common/condition"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCondition is a mock of Condition interface.
type MockCondition struct {
	ctrl     *gomock.Controller
	recorder *MockConditionMockRecorder
}

// MockConditionMockRecorder is the mock recorder for MockCondition.
type MockConditionMockRecorder struct {
	mock *MockCondition
}

// NewMockCondition creates a new mock instance.
func NewMockCondition(ctrl *gomock.Controller) *MockCondition {
	mock := &MockCondition{ctrl: ctrl}
	mock.recorder = &MockConditionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCondition) EXPECT() *MockConditionMockRecorder {
	return m.recorder
}

// Convert mocks base method.
func (m *MockCondition) Convert(ctx context.Context, vectorizer func(context.Context, []string) ([]condition.VectorResp, error)) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert", ctx, vectorizer)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Convert indicates an expected call of Convert.
func (mr *MockConditionMockRecorder) Convert(ctx, vectorizer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert", reflect.TypeOf((*MockCondition)(nil).Convert), ctx, vectorizer)
}

// Convert2SQL mocks base method.
func (m *MockCondition) Convert2SQL(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert2SQL", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Convert2SQL indicates an expected call of Convert2SQL.
func (mr *MockConditionMockRecorder) Convert2SQL(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert2SQL", reflect.TypeOf((*MockCondition)(nil).Convert2SQL), ctx)
}
