Name: kw-graph
Host: 0.0.0.0
Port: 6480
Timeout: 600000
MaxBytes: 100000000

Log:
  Mode: console
  ServiceName: kw-graph
  Stat: false
  Level: info

DataSources:
  Host: 127.0.0.1
  Port: 3306
  Config: ""
  DBName: kweaver
  Username: root
  Password: kwever123!QWE
  DriverName: mysql

Builder:
  BuilderHost: kw-builder
  BuilderPort: 6475

Redis:
  ConnectType: standalone
  SentinelMasterName: mymaster
  SentinelName: root
  SentinelPass: kwever123!QWE
  RedisHost: 127.0.0.1
  RedisPort: 6379
  # 低版本redis，username环境变量为空，go-zero读取yaml文件这里也应该为空
  # 注意： 本地debug完成后，提交代码不要赋值
  RedisUser:
  RedisPass: kwever123!QWE
  RedisReadHost: xxx.dcs.huaweicloud.com
  RedisReadPort: 26379
  # 华为云低版本redis username环境变量为空，go-zero读取yaml文件这里也应该为空
  # 注意： 本地debug完成后，提交代码不要赋值
  RedisReadUser:
  RedisReadPass: kwever123!QWE
  RedisWriteHost: xxx-readonly.dcs.huaweicloud.com
  RedisWritePort: 26379
  # 华为云低版本redis username环境变量为空，go-zero读取yaml文件这里也应该为空
  # 注意： 本地debug完成后，提交代码不要赋值
  RedisWriteUser:
  RedisWritePass: kwever123!QWE

Nebula:
  NebulaHost: 127.0.0.1
  NebulaPort: 9669
  NebulaUser: root
  NebulaPass: kwever123!QWE

OpenSearch:
  OpenSearchHost: 127.0.0.1
  OpenSearchPort: 9200
  OpenSearchUser: admin
  OpenSearchPass: kwever123!QWE
