# -*- coding:utf-8 -*-

Builder_FunctionController_CreateFunction_UnknownError = 'Builder.FunctionController.CreateFunction.UnknownError'
Builder_FunctionController_CreateFunction_ParamError = 'Builder.FunctionController.CreateFunction.ParamError'
Builder_FunctionService_CreateFunction_KnwIdNotExist = 'Builder.FunctionService.CreateFunction.KnwIdNotExist'
Builder_FunctionService_CreateFunction_DuplicatedName = "Builder.FunctionService.CreateFunction.DuplicatedName"

Builder_FunctionController_EditFunction_UnknownError = 'Builder.FunctionController.EditFunction.UnknownError'
Builder_FunctionController_EditFunction_ParamError = 'Builder.FunctionController.EditFunction.ParamError'
Builder_FunctionService_EditFunction_FunctionIdNotExist = 'Builder.FunctionService.EditFunction.FunctionIdNotExist'
Builder_FunctionService_EditFunction_KnwIdNotExist = 'Builder.FunctionService.EditFunction.KnwIdNotExist'
Builder_FunctionService_EditFunction_DuplicatedName = "Builder.FunctionService.EditFunction.DuplicatedName"

Builder_FunctionController_DeleteFunction_UnknownError = 'Builder.FunctionController.DeleteFunction.UnknownError'
Builder_FunctionController_DeleteFunction_ParamError = 'Builder.FunctionController.DeleteFunction.ParamError'

Builder_FunctionController_GetFunctionList_UnknownError = 'Builder.FunctionController.GetFunctionList.UnknownError'
Builder_FunctionController_GetFunctionList_ParamError = 'Builder.FunctionController.GetFunctionList.ParamError'
Builder_FunctionService_GetFunctionList_KnwIdNotExist = 'Builder.FunctionService.GetFunctionList.KnwIdNotExist'

Builder_FunctionController_GetFunctionById_UnknownError = 'Builder.FunctionController.GetFunctionById.UnknownError'
Builder_FunctionController_GetFunctionById_ParamError = 'Builder.FunctionController.GetFunctionById.ParamError'
Builder_FunctionService_GetFunctionById_FunctionIdNotExist = 'Builder.FunctionService.GetFunctionById.FunctionIdNotExist'
