# -*- coding:utf-8 -*-
Builder_OntologyController_PredictOntology_ParamError = 'Builder.OntologyController.PredictOntology.ParamError'
Builder_OntologyController_PredictOntology_UnknownError = 'Builder.OntologyController.PredictOntology.UnknownError'
Builder_OntologyController_PredictOntology_AsyncTaskInternalError = 'Builder.OntologyController.PredictOntology.AsyncTaskInternalError'

Builder_OtlService_PredictOntology_DataSourceInConsistent = 'Builder.OtlService.PredictOntology.DataSourceInConsistent'
Builder_OtlService_PredictOntology_GraphIdNotExist = 'Builder.OtlService.PredictOntology.GraphIdNotExist'
Builder_OtlService_PredictOntology_DsIdNotExist = 'Builder.OtlService.PredictOntology.DsIdNotExist'
Builder_OtlService_PredictOntology_GetAnnotationOtlError = 'Builder.OtlService.PredictOntology.GetAnnotationOtlError'
Builder_OtlService_PredictOntology_UnknownError = 'Builder.OtlService.PredictOntology.UnknownError'
Builder_OtlService_PredictOntology_GetExtractionRulesFailed = 'Builder.OtlService.PredictOntology.GetExtractionRulesFailed'

Builder_OntologyController_InfoExtractTask_ParamError = 'Builder.OntologyController.InfoExtractTask.ParamError'
Builder_OntologyController_InfoExtractTask_UnknownError = 'Builder.OntologyController.InfoExtractTask.UnknownError'

Builder_OtlService_GetExtractTaskRes_CeleryTaskIdNotExist = 'Builder.OtlService.GetExtractTaskRes.CeleryTaskIdNotExist'

Builder_OntologyController_DataPreview_ParamError = 'Builder.OntologyController.DataPreview.ParamError'
Builder_OntologyController_DataPreview_UnknownError = 'Builder.OntologyController.DataPreview.UnknownError'

Builder_OtlService_PreviewData_DsIdNotExist = 'Builder.OtlService.PreviewData.DsIdNotExist'
Builder_OtlService_PreviewData_DataSourceInConsistent = 'Builder.OtlService.PreviewData.DataSourceInConsistent'
Builder_OtlService_PreviewData_PreviewMysqlError = 'Builder.OtlService.PreviewData.PreviewMysqlError'
Builder_OtlService_PreviewData_PasswordError = 'Builder.OtlService.PreviewData.PasswordError'
Builder_OtlService_PreviewData_FileNotExist = 'Builder.OtlService.PreviewData.FileNotExist'
Builder_OtlService_PreviewData_PreviewHiveError = 'Builder.OtlService.PreviewData.PreviewHiveError'
Builder_OtlService_PreviewData_UnsupportedFileType = 'Builder.OtlService.PreviewData.UnsupportedFileType'
Builder_OtlService_PreviewData_PreviewASError = 'Builder.OtlService.PreviewData.PreviewASError'
Builder_OtlService_PreviewData_PreviewKingbaseesError = 'Builder.OtlService.PreviewData.PreviewKingbaseesError'
Builder_OtlService_PreviewData_PreviewSqlServerError = 'Builder.OtlService.PreviewData.PreviewSqlServerError'
Builder_OtlService_PreviewData_PreviewPostgreSQLError = 'Builder.OtlService.PreviewData.PreviewPostgreSQLError'
Builder_OtlService_PreviewData_PreviewClickHouseError = 'Builder.OtlService.PreviewData.PreviewClickHouseError'

Builder_OntologyController_BuildOntoTask_ParamError = 'Builder.OntologyController.BuildOntoTask.ParamError'
Builder_OntologyController_BuildOntoTask_UnknownError = 'Builder.OntologyController.BuildOntoTask.UnknownError'

Builder_OntoBlue_OtlTask_UnknownError = 'Builder.OntoBlue.OtlTask.UnknownError'
Builder_OntoBlue_OtlTask_TaskNumberMaximum = 'Builder.OntoBlue.OtlTask.TaskNumberMaximum'
Builder_OntoBlue_OtlTask_OntologyIdNotExist = 'Builder.OntoBlue.OtlTask.OntologyIdNotExist'
Builder_OntoBlue_OtlTask_DsIdNotExist = 'Builder.OntoBlue.OtlTask.DsIdNotExist'

Builder_OtlController_GetTable_ParamError = 'Builder.OtlController.GetTable.ParamError'

Builder_OtlController_GetTaskInfo_ParamError = 'Builder.OtlController.GetTaskInfo.ParamError'
Builder_OtlController_GetTaskInfo_UnknownError = 'Builder.OtlController.GetTaskInfo.UnknownError'

Builder_OntologyController_SaveOntology_ParamsError = 'Builder.OntologyController.SaveOntology.ParamsError'
Builder_OntologyController_SaveOntology_UnknownError = 'Builder.OntologyController.SaveOntology.UnknownError'

Builder_OtlService_OntologySave_OtlNameDuplicate = 'Builder.OtlService.OntologySave.OtlNameDuplicate'
Builder_OtlService_OntologySave_KnwIdNotExist = 'Builder.OtlService.OntologySave.KnwIdNotExist'

Builder_OntologyController_EditOntology_ParamError = 'Builder.OntologyController.EditOntology.ParamError'
Builder_OntologyController_EditOntology_UnknownError = 'Builder.OntologyController.EditOntology.UnknownError'

Builder_OtlService_EditOntology_OtlIdNotExist = 'Builder.OtlService.EditOntology.OtlIdNotExist'
Builder_OtlService_OntologyEdit_OtlNameDuplicate = 'Builder.OtlService.OntologyEdit.OtlNameDuplicate'

Builder_OntologyController_DelOntology_ParamError = 'Builder.OntologyController.DelOntology.ParamError'
Builder_OntologyController_DelOntology_UnknownError = 'Builder.OntologyController.DelOntology.UnknownError'

Builder_OtlService_DeleteOntology_KnwIdNotExist = 'Builder.OtlService.DeleteOntology.KnwIdNotExist'
Builder_OtlService_DeleteOntology_OtlNotExistInKnw = 'Builder.OtlService.DeleteOntology.OtlNotExistInKnw'

Builder_OntologyController_GetAll_ParamError = 'Builder.OntologyController.GetAll.ParamError'
Builder_OntologyController_GetAll_UnknownError = 'Builder.OntologyController.GetAll.UnknownError'

Builder_OtlService_GetAll_KnwIdNotExist = 'Builder.OtlService.GetAll.KnwIdNotExist'

Builder_OntologyController_Otl_ParamError = 'Builder.OntologyController.Otl.ParamError'
Builder_OntologyController_Otl_UnknownError = 'Builder.OntologyController.Otl.UnknownError'

Builder_OtlService_GetById_OtlIdNotExist = 'Builder.OtlService.GetById.OtlIdNotExist'

Builder_OntologyController_ImportTask_ParamError = 'Builder.OntologyController.ImportTask.ParamError'
Builder_OntologyController_ImportTask_UnknownError = 'Builder.OntologyController.ImportTask.UnknownError'
Builder_OntologyController_ImportTask_KnwIdNotExist = 'Builder.OntologyController.ImportTask.KnwIdNotExist'
Builder_OntologyController_ImportTask_AsyncTaskInternalError = 'Builder.OntologyController.ImportTask.AsyncTaskInternalError'

Builder_OntologyController_GetImportTask_ParamError = 'Builder.OntologyController.GetImportTask.ParamError'
Builder_OntologyController_GetImportTask_UnknownError = 'Builder.OntologyController.GetImportTask.UnknownError'
Builder_OtlService_GetImportTask_CeleryTaskIdNotExists = 'Builder.OtlService.GetImportTask.CeleryTaskIdNotExists'

Builder_OntologyController_DownloadOntoTemplate_ParamError = 'Builder.OntologyController.DownloadOntoTemplate.ParamError'
Builder_OntologyController_DownloadOntoTemplate_UnknownError = 'Builder.OntologyController.DownloadOntoTemplate.UnknownError'

Builder_OntologyController_ExportOnto_ParamError = 'Builder.OntologyController.ExportOnto.ParamError'
Builder_OntologyController_ExportOnto_UnknownError = 'Builder.OntologyController.ExportOnto.UnknownError'
Builder_OtlService_ExportOnto_OtlIdNotExist = 'Builder.OtlService.ExportOnto.OtlIdNotExist'
Builder_OtlService_ExportOnto_OtlIdNotInOtlLibrary = 'Builder.OtlService.ExportOnto.OtlIdNotInOtlLibrary'

Builder_OntologyController_UpdateName_ParamError = 'Builder.OntologyController.UpdateName.ParamError'
Builder_OntologyController_UpdateName_UnknownError = 'Builder.OntologyController.UpdateName.UnknownError'
Builder_OtlService_UpdateName_OtlIdNotExist = 'Builder.OtlService.UpdateName.OtlIdNotExist'
Builder_OtlService_UpdateName_OtlNameDuplicate = 'Builder.OtlService.UpdateName.OtlNameDuplicate'

Builder_OntologyController_SqlExtract_ParamError = 'Builder.OntologyController.SqlExtract.ParamError'
Builder_OntologyController_SqlExtract_UnknownError = 'Builder.OntologyController.SqlExtract.UnknownError'

Builder_OtlService_SqlExtract_DsIdNotExist = 'Builder.OtlService.SqlExtract.DsIdNotExist'
Builder_OtlService_SqlExtract_DataSourceError = 'Builder.OtlService.SqlExtract.DataSourceError'
Builder_OtlService_SqlExtract_SqlError = 'Builder.OtlService.SqlExtract.SqlError'
Builder_OtlService_SqlExtract_TimeOutError = 'Builder.OtlService.SqlExtract.TimeOutError'
Builder_OtlService_SqlExtract_PasswordError = 'Builder.OtlService.SqlExtract.PasswordError'
Builder_OtlService_SqlExtract_FieldRepeats = 'Builder.OtlService.SqlExtract.FieldRepeats'
Builder_OtlService_SqlExtract_EmptyData = 'Builder.OtlService.SqlExtract.EmptyData'

Builder_OntologyController_SqlPreViewData_ParamError = 'Builder.OntologyController.SqlPreViewData.ParamError'
Builder_OntologyController_SqlPreviewData_UnknownError = 'Builder.OntologyController.SqlPreviewData.UnknownError'
