# -*- coding:utf-8 -*-

Builder_SubgraphService_CreateSubgraphConfig_GraphIdNotExist = 'Builder.SubgraphService.CreateSubgraphConfig.GraphIdNotExist'
Builder_SubgraphService_CreateSubgraphConfig_OntologyNotExist = 'Builder.SubgraphService.CreateSubgraphConfig.OntologyNotExist'
Builder_SubgraphService_CreateSubgraphConfig_DuplicateName = 'Builder.SubgraphService.CreateSubgraphConfig.DuplicateName'
Builder_SubgraphService_CreateSubgraphConfig_UnexpectedClass = 'Builder.SubgraphService.CreateSubgraphConfig.UnexpectedClass'
Builder_SubgraphService_CreateSubgraphConfig_GraphRunning = 'Builder.SubgraphService.CreateSubgraphConfig.GraphRunning'

Builder_SubgraphService_EditSubgraphConfig_GraphIdNotExist = 'Builder.SubgraphService.EditSubgraphConfig.GraphIdNotExist'
Builder_SubgraphService_EditSubgraphConfig_SubgraphIdNotExist = 'Builder.SubgraphService.EditSubgraphConfig.SubgraphIdNotExist'
Builder_SubgraphService_EditSubgraphConfig_DuplicateName = 'Builder.SubgraphService.EditSubgraphConfig.DuplicateName'
Builder_SubgraphService_EditSubgraphConfig_UnexpectedClass = 'Builder.SubgraphService.EditSubgraphConfig.UnexpectedClass'
Builder_SubgraphService_EditSubgraphConfig_GraphRunning = 'Builder.SubgraphService.EditSubgraphConfig.GraphRunning'
Builder_SubgraphService_EditSubgraphConfig_UngroupedCannotRename = 'Builder.SubgraphService.EditSubgraphConfig.UngroupedCannotRename'
Builder_SubgraphService_EditSubgraphConfig_CannotRenamedToUngrouped = 'Builder.SubgraphService.EditSubgraphConfig.CannotRenamedToUngrouped'

Builder_SubgraphService_SubgraphSaveNoCheck_GraphIdNotExist = 'Builder_SubgraphService_SubgraphSaveNoCheck_GraphIdNotExist'
Builder_SubgraphService_SubgraphSaveNoCheck_GraphRunning = 'Builder_SubgraphService_SubgraphSaveNoCheck_GraphRunning'
Builder_SubgraphService_SubgraphSaveNoCheck_CannotRenamedToUngrouped = 'Builder_SubgraphService_SubgraphSaveNoCheck_CannotRenamedToUngrouped'
Builder_SubgraphService_SubgraphSaveNoCheck_SubgraphIdNotExist = 'Builder_SubgraphService_SubgraphSaveNoCheck_SubgraphIdNotExist'
Builder_SubgraphService_SubgraphSaveNoCheck_UngroupedCannotRename = 'Builder_SubgraphService_SubgraphSaveNoCheck_UngroupedCannotRename'

Builder_SubgraphService_GetSubgraphList_GraphIdNotExist = 'Builder.SubgraphService.GetSubgraphList.GraphIdNotExist'

Builder_SubgraphService_GetSubgraphConfig_SubgraphIdNotExist = 'Builder.SubgraphService.GetSubgraphConfig.SubgraphIdNotExist'

Builder_SubgraphService_DeleteSubgraphConfig_GraphIdNotExist = 'Builder.SubgraphService.DeleteSubgraphConfig.GraphIdNotExist'
Builder_SubgraphService_DeleteSubgraphConfig_DeleteUngrouped = 'Builder.SubgraphService.DeleteSubgraphConfig.DeleteUngrouped'
Builder_SubgraphService_DeleteSubgraphConfig_GraphRunning = 'Builder.SubgraphService.DeleteSubgraphConfig.GraphRunning'
Builder_SubgraphService_DeleteSubgraphConfig_GraphWaiting = 'Builder.SubgraphService.DeleteSubgraphConfig.GraphWaiting'
Builder_SubgraphService_DeleteSubgraphConfig_SubgraphIdNotExist = 'Builder.SubgraphService.DeleteSubgraphConfig.SubgraphIdNotExist'
