definitions:
  kw_errors.Error:
    properties:
      Description:
        type: string
      ErrorCode:
        type: string
      ErrorDetails:
        items: {}
        type: array
      ErrorLink:
        type: string
      Solution:
        type: string
    type: object
  vo.ConnTestVo:
    properties:
      ip:
        items:
          type: string
        type: array
      password:
        maxLength: 150
        type: string
      port:
        items:
          type: string
        type: array
      type:
        enum:
        - orientdb
        - nebula
        - opensearch
        type: string
      user:
        maxLength: 50
        type: string
    required:
    - password
    - user
    type: object
  vo.GraphDBUpdateVo:
    properties:
      id:
        type: integer
      ip:
        items:
          type: string
        type: array
      name:
        type: string
      password:
        maxLength: 150
        type: string
      port:
        items:
          type: string
        type: array
      type:
        enum:
        - orientdb
        - nebula
        - opensearch
        type: string
      user:
        maxLength: 50
        type: string
    required:
    - password
    - user
    type: object
  vo.GraphDBVo:
    properties:
      id:
        type: integer
      ip:
        items:
          type: string
        type: array
      name:
        type: string
      osId:
        minimum: 1
        type: integer
      password:
        maxLength: 150
        type: string
      port:
        items:
          type: string
        type: array
      type:
        enum:
        - orientdb
        - nebula
        - opensearch
        type: string
      user:
        maxLength: 50
        type: string
    required:
    - osId
    - password
    - user
    type: object
  vo.IdVo:
    properties:
      id:
        type: integer
    type: object
  vo.ListVo:
    properties:
      data: {}
      total:
        type: integer
    type: object
  vo.OpenSearchIdVo:
    properties:
      id:
        type: integer
    type: object
  vo.OpenSearchTestVo:
    properties:
      ip:
        items:
          type: string
        type: array
      password:
        maxLength: 150
        type: string
      port:
        items:
          type: string
        type: array
      user:
        maxLength: 50
        type: string
    required:
    - password
    - user
    type: object
  vo.OpenSearchUpdateVo:
    properties:
      id:
        type: integer
      ip:
        items:
          type: string
        type: array
      name:
        type: string
      password:
        maxLength: 150
        type: string
      port:
        items:
          type: string
        type: array
      user:
        maxLength: 50
        type: string
    required:
    - password
    - user
    type: object
  vo.OpenSearchVo:
    properties:
      created:
        type: integer
      id:
        type: integer
      ip:
        items:
          type: string
        type: array
      name:
        type: string
      password:
        maxLength: 150
        type: string
      port:
        items:
          type: string
        type: array
      updated:
        type: integer
      user:
        maxLength: 50
        type: string
    required:
    - password
    - user
    type: object
info:
  contact: {}
  description: 欢迎使用KWeaver 1.0 OpenAPI
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: KWeaver API
  version: "1.0"
paths:
  /api/studio/v1/graphdb:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Query storage configuration information based on id
      parameters:
      - description: Storage configuration id
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Store configuration information
          schema:
            $ref: '#/definitions/vo.GraphDBVo'
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Query storage configuration information based on id
      tags:
      - Studio
  /api/studio/v1/graphdb/add:
    post:
      consumes:
      - application/json
      description: Add storage configuration
      parameters:
      - description: Storage configuration parameters
        in: body
        name: graphDBVo
        required: true
        schema:
          $ref: '#/definitions/vo.GraphDBVo'
      produces:
      - application/json
      responses:
        "200":
          description: Added storage configuration id
          schema:
            type: number
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Add storage configuration
      tags:
      - Studio
  /api/studio/v1/graphdb/delete:
    post:
      consumes:
      - application/json
      description: Delete storage configuration based on id
      parameters:
      - description: Storage configuration id
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/vo.IdVo'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Delete storage configuration based on id
      tags:
      - Studio
  /api/studio/v1/graphdb/graph/list:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Query the associated graph based on the storage configuration id
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Quantity per page
        in: query
        name: size
        type: integer
      - description: Storage configuration id
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Associated graph information
          schema:
            $ref: '#/definitions/vo.ListVo'
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Query the associated graph based on the storage configuration id
      tags:
      - Studio
  /api/studio/v1/graphdb/list:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Get storage configurations and graphs in storage configurations
        according to page and size
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Quantity per page
        in: query
        name: size
        type: integer
      - description: Configuration name
        in: query
        name: name
        type: string
      - description: Configuration type
        in: query
        name: type
        type: string
      - description: Order field
        in: query
        name: orderField
        type: string
      - description: Order type
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Storage configuration list
          schema:
            $ref: '#/definitions/vo.ListVo'
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Get storage configurations and graphs in storage configurations according
        to page and size
      tags:
      - Studio
  /api/studio/v1/graphdb/test:
    post:
      consumes:
      - application/json
      description: Test whether the storage configuration information is correct
      parameters:
      - description: Storage configuration information to be tested
        in: body
        name: testVo
        required: true
        schema:
          $ref: '#/definitions/vo.ConnTestVo'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Test whether the storage configuration information is correct
      tags:
      - Studio
  /api/studio/v1/graphdb/update:
    post:
      consumes:
      - application/json
      description: Update storage configuration based on id
      parameters:
      - description: Storage configuration parameters
        in: body
        name: graphDBUpdateVo
        required: true
        schema:
          $ref: '#/definitions/vo.GraphDBUpdateVo'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Update storage configuration based on id
      tags:
      - Studio
  /api/studio/v1/opensearch:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Query opensearch configuration information based on id
      parameters:
      - description: opensearch configuration id
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: opensearch configuration
          schema:
            $ref: '#/definitions/vo.OpenSearchVo'
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Query opensearch configuration information based on id
      tags:
      - Studio
  /api/studio/v1/opensearch/add:
    post:
      consumes:
      - application/json
      description: Add opensearch configuration
      parameters:
      - description: Added opensearch configuration
        in: body
        name: opensearchVo
        required: true
        schema:
          $ref: '#/definitions/vo.OpenSearchVo'
      produces:
      - application/json
      responses:
        "200":
          description: Added opensearch configuration id
          schema:
            type: number
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Add opensearch configuration
      tags:
      - Studio
  /api/studio/v1/opensearch/delete:
    post:
      consumes:
      - application/json
      description: Delete opensearch configuration based on id
      parameters:
      - description: opensearch configuration id
        in: body
        name: idVo
        required: true
        schema:
          $ref: '#/definitions/vo.OpenSearchIdVo'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Delete opensearch configuration based on id
      tags:
      - Studio
  /api/studio/v1/opensearch/list:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Get opensearch information based on page and size
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Quantity per page
        in: query
        name: size
        type: integer
      - description: Record name
        in: query
        name: name
        type: string
      - description: Order field
        in: query
        name: orderField
        type: string
      - description: Order type
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: opensearch configuration list
          schema:
            $ref: '#/definitions/vo.ListVo'
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Get opensearch information based on page and size
      tags:
      - Studio
  /api/studio/v1/opensearch/test:
    post:
      consumes:
      - application/json
      description: Test whether the opensearch configuration is correct
      parameters:
      - description: opensearch configuration to be tested
        in: body
        name: osVo
        required: true
        schema:
          $ref: '#/definitions/vo.OpenSearchTestVo'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Test whether the opensearch configuration is correct
      tags:
      - Studio
  /api/studio/v1/opensearch/update:
    post:
      consumes:
      - application/json
      description: Update opensearch configuration based on id
      parameters:
      - description: Updated opensearch configuration
        in: body
        name: opensearchUpdateVo
        required: true
        schema:
          $ref: '#/definitions/vo.OpenSearchUpdateVo'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Parameter error
          schema:
            $ref: '#/definitions/kw_errors.Error'
        "500":
          description: Server internal error
          schema:
            $ref: '#/definitions/kw_errors.Error'
      summary: Update opensearch configuration based on id
      tags:
      - Studio
  /api/studio/v1/swaggerDoc:
    get:
      description: query api documentation
      produces:
      - application/json
      responses:
        "200":
          description: swagger api documentation
          schema:
            type: object
      summary: query api documentation
      tags:
      - Studio
swagger: "2.0"
