replicaCount: 1

namespace: kweaver

image:
  registry: acr.aishu.cn
  repository: /ad/kw-engine
  tag: latest
  pullPolicy: IfNotPresent
  name: kw-engine

service:
  type: ClusterIP
  port: 6474
  targetPort: 6474
  
volumes:  
  hostPath: /kweaver/deploy/kw-k8s/conf/kwconfig/