# -*- coding:utf-8 -*-
Builder_CeleryController_GetSubgraphConfig_ParamError = 'Builder.CeleryController.GetSubgraphConfig.ParamError'
Builder_CeleryController_GetSubgraphConfig_UnknownError = 'Builder.CeleryController.GetSubgraphConfig.UnknownError'

Builder_TaskService_GetSubgraphConfig_TaskIdNotExist = 'Builder.TaskService.GetSubgraphConfig.TaskIdNotExist'

Builder_CeleryController_BatchExecuteTask_ParamError = 'Builder.CeleryController.BatchExecuteTask.ParamError'
Builder_CeleryController_BatchExecuteTask_UnknownError = 'Builder.CeleryController.BatchExecuteTask.UnknownError'
Builder_CeleryController_BatchExecuteTask_GraphIdNotExist = 'Builder.CeleryController.BatchExecuteTask.GraphIdNotExist'

Builder_CeleryBlue_TaskBatch_UnknownError = 'Builder.CeleryBlue.TaskBatch.UnknownError'
Builder_CeleryBlue_TaskBatch_SubgraphIdNotExist = 'Builder.CeleryBlue.TaskBatch.SubgraphIdNotExist'
Builder_CeleryBlue_TaskBatch_GraphDBNotExist = 'Builder.CeleryBlue.TaskBatch.GraphDBNotExist'
Builder_CeleryBlue_TaskBatch_GraphInEditingStatus = 'Builder.CeleryBlue.TaskBatch.GraphInEditingStatus'
Builder_CeleryBlue_TaskBatch_GraphInRunningOrWaiting = 'Builder.CeleryBlue.TaskBatch.GraphInRunningOrWaiting'

Builder_CeleryController_GetProgress_ParamError = 'Builder.CeleryController.GetProgress.ParamError'
Builder_CeleryBlue_GetProgressByTaskId_TaskIdNotExist = 'Builder.CeleryBlue.GetProgressByTaskId.TaskIdNotExist'
Builder_CeleryController_GetProgress_UnknownError = 'Builder.CeleryController.GetProgress.UnknownError'
Builder_CeleryBlue_GetProgressByTaskId_UnknownError = 'Builder.CeleryBlue.GetProgressByTaskId.UnknownError'

Builder_CeleryController_StopTask_ParamError = 'Builder.CeleryController.StopTask.ParamError'
Builder_CeleryController_StopTask_UnknownError = 'Builder.CeleryController.StopTask.UnknownError'
Builder_CeleryBlue_StopTask_UnknownError = 'Builder.CeleryBlue.StopTask.UnknownError'
Builder_CeleryBlue_StopTask_TaskNotExist = 'Builder.CeleryBlue.StopTask.TaskNotExist'
Builder_CeleryBlue_StopTask_TerminationNotAllowed = 'Builder.CeleryBlue.StopTask.TerminationNotAllowed'

Builder_CeleryController_GetAllTask_UnknownError = 'Builder.CeleryController.GetAllTask.UnknownError'
Builder_CeleryController_GetAllTask_ParamError = 'Builder.CeleryController.GetAllTask.ParamError'
Builder_CeleryController_GetAllTask_GraphIdNotExist = 'Builder.CeleryController.GetAllTask.GraphIdNotExist'
Builder_CeleryBlue_GetAllTask_UnknownError = 'Builder.CeleryBlue.GetAllTask.UnknownError'

Builder_CeleryController_DeleteTask_UnknownError = 'Builder.CeleryController.DeleteTask.UnknownError'
Builder_CeleryController_DeleteTask_ParamError = 'Builder.CeleryController.DeleteTask.ParamError'
Builder_CeleryController_DeleteTask_GraphIdNotExist = 'Builder.CeleryController.DeleteTask.GraphIdNotExist'
Builder_CeleryBlue_DeleteTask_UnknownError = 'Builder.CeleryBlue.DeleteTask.UnknownError'