# -*- coding:utf-8 -*-

# 领域智商计算错误
Builder_Dao_AsyncTaskDao_Update_ServerError = 'Builder.Dao.AsyncTaskDao.Update.ServerError'
Builder_Dao_AsyncTaskDao_Update_SQLSyntaxError = 'Builder.Dao.AsyncTaskDao.Update.SQLSyntaxError'

Builder_IntelligenceCalculateService_SendTask_GraphWaitStatusError = 'Builder.IntelligenceCalculateService.SendTask.GraphWaitStatusError'
Builder_IntelligenceCalculateService_SendTask_GraphConfigStatusError = 'Builder.IntelligenceCalculateService.SendTask.GraphConfigStatusError'
Builder_IntelligenceCalculateService_SendTask_GraphRunStatusError = 'Builder.IntelligenceCalculateService.SendTask.GraphRunStatusError'
Builder_IntelligenceCalculateService_SendTask_GraphFailStatusError = 'Builder.IntelligenceCalculateService.SendTask.GraphFailStatusError'
Builder_IntelligenceCalculateService_SendTask_GraphInvalidStatusError = 'Builder.IntelligenceCalculateService.SendTask.GraphInvalidStatusError'
Builder_IntelligenceCalculateService_SendTask_CallAsyncTaskError = 'Builder.IntelligenceCalculateService.SendTask.CallAsyncTaskError'
Builder_IntelligenceCalculateService_SendTask_AsyncTaskInternalError = 'Builder.IntelligenceCalculateService.SendTask.AsyncTaskInternalError'

Builder_IntelligenceQueryService_QueryGraphIntelligence_QueryError = 'Builder.IntelligenceQueryService.QueryGraphIntelligence.QueryError'
Builder_IntelligenceQueryService_QueryGraphIntelligence_GraphNotExistsError = 'Builder.IntelligenceQueryService.QueryGraphIntelligence.GraphNotExistsError'

Builder_IntelligenceQueryService_QueryNetworkIntelligence_QueryError = 'Builder.IntelligenceQueryService.QueryNetworkIntelligence.QueryError'

Builder_IntelligenceQueryService_QueryNetworkIntelligence_KnwNotExist = 'Builder.IntelligenceQueryService.QueryNetworkIntelligence.KnwNotExist'
