apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    pv: {{ .Values.image.name }}
  name: {{ .Values.image.name }}
spec:
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteOnce
#  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
#  nfs:
#    path: {{ .Values.storage.local.path }}
#    server: {{ .Values.storage.local.host }}
  local:
    path: {{ .Values.storage.local.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: "In"
              values:
                - {{ .Values.storage.local.host }}