server:
  ip: 0.0.0.0
  port: 6474
  debug: true
orient:
  user: admin
  password: admin
  ip:  kc-topic-orientdb
  port: 2480
  db: kc-topic
algServer:
  ip: kw-algserver
  port: 8080
builderServer:
  ip: kw-builder
  port: 6475
mariadb:
  host: rds-proton-rds-mariadb-cluster
  port: 3320
  user: user
  password: password
  database: database


