server:
  ip: 0.0.0.0
  port: 6474
  debug: true
orient:
  user: admin
  password: admin
  ip:  kc-topic-orientdb
  port: 2480
  db: kc-topic
algServer:
  #ip: kw-alg-server
  ip: 127.0.0.1
  port: 8080
builderServer:
  ip: kw-builder
  port: 6475
mariadb:
  #ip: rds-proton-rds-mariadb-cluster
  ip: 10.4.106.255
  port: 3320
  user: anydata
  password: Qwe123!@#
  db: anydata


