/**
 * 领域智商计算状态
 */
export enum CALCULATE_STATUS {
  NOT_CALCULATE = 'NOT_CALCULATE',
  IN_CALCULATING = 'IN_CALCULATING',
  CALCULATED = 'CALCULATED',
  CALCULATE_FAIL = 'CALCULATE_FAIL',
  CALCULATE_CANCEL = 'CALCULATE_CANCEL'
}
