/**
 * 模型的属性显示名
 * 名称映射文档地址：https://confluence.aishu.cn/pages/viewpage.action?pageId=183146667
 * 可按照以下代码提取
 * const rows = document.querySelectorAll('tbody > tr')
 * rows.forEach(element => {
 *   const name = element.children[3].innerText
 *   const alias = element.children[4].innerText
 * })
 */
export const GRAPH_MODEL_ALIAS: Record<string, string> = {
  name: '名称',
  journal: '发表期刊',
  publish_date: '发布时间',
  financing: '融资',
  financing_amount: '融资金额',
  datetime: '举行时间',
  path: '路径',
  gns: '文档id',
  create_time: '创建时间',
  rev: '版本号',
  subject_id: '主题id',
  subject_path: '主题路径',
  subject_fold: '主题目录',
  subject_desc: '主题描述',
  confidence: '置信度',
  adlabel_kcid: 'AD或者KC的标签',
  kc_topic_tags: 'KC主题标签',
  type_as: '是否来自AS',
  type_sa: '是否来自句法分析',
  type_nw: '是否来自新词',
  type_kc: '是否来自KC',
  creator: '创建者',
  editor: '编辑者',
  file_type: '文件类型',
  modified_time: '修改时间',
  level: '级别',
  weight: '权重',
  score: '主题文档分数',
  id: '合同id',
  content: '内容',
  number: '合同编号',
  currency: '合同金额',
  amount: '币种',
  sign_date: '签约日期',
  account_name: '账户名称',
  bank: '开户行',
  bank_number: '账号',
  tax_rate: '税率',
  tax_amount: '税额',
  amount_without_tax: '不含税金额',
  height: '身高',
  birthday: '出生日期',
  minority: '民族',
  altitude: '海拔',
  publishing_company: '出版社',
  courtesy_name: '字',
  dynasty: '朝代',
  literary_name: '号',
  area: '面积',
  postcode: '邮政编码',
  population: '人口数量',
  study_duration: '修业年限',
  professional_code: '专业代码',
  order_of: '目',
  release_date: '上映时间',
  registered_capital: '注册资本',
  establishment_date: '成立日期',
  abbreviation: '简称',
  docComponentId: '组成部分id',
  docComponentClassify: '组成部分分类',
  docComponentContent: '组成部分内容',
  docClassify: '文档分类',
  docPath: '文档路径',
  docFormat: '文档格式',
  docSize: '文档大小',
  docCreatedTime: '文档创建时间',
  docUpdatedTime: '文档修改时间',
  docTitle: '文档标题',
  docLabel: '文档标签',
  docLink: '文档链接',
  docAuthor: '文档作者',
  docVersion: '文档版本'
};
