// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/object_type_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockObjectTypeService is a mock of ObjectTypeService interface.
type MockObjectTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockObjectTypeServiceMockRecorder
}

// MockObjectTypeServiceMockRecorder is the mock recorder for MockObjectTypeService.
type MockObjectTypeServiceMockRecorder struct {
	mock *MockObjectTypeService
}

// NewMockObjectTypeService creates a new mock instance.
func NewMockObjectTypeService(ctrl *gomock.Controller) *MockObjectTypeService {
	mock := &MockObjectTypeService{ctrl: ctrl}
	mock.recorder = &MockObjectTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectTypeService) EXPECT() *MockObjectTypeServiceMockRecorder {
	return m.recorder
}

// CheckObjectTypeExistByID mocks base method.
func (m *MockObjectTypeService) CheckObjectTypeExistByID(ctx context.Context, knID, otID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckObjectTypeExistByID", ctx, knID, otID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckObjectTypeExistByID indicates an expected call of CheckObjectTypeExistByID.
func (mr *MockObjectTypeServiceMockRecorder) CheckObjectTypeExistByID(ctx, knID, otID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckObjectTypeExistByID", reflect.TypeOf((*MockObjectTypeService)(nil).CheckObjectTypeExistByID), ctx, knID, otID)
}

// CheckObjectTypeExistByName mocks base method.
func (m *MockObjectTypeService) CheckObjectTypeExistByName(ctx context.Context, knID, otName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckObjectTypeExistByName", ctx, knID, otName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckObjectTypeExistByName indicates an expected call of CheckObjectTypeExistByName.
func (mr *MockObjectTypeServiceMockRecorder) CheckObjectTypeExistByName(ctx, knID, otName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckObjectTypeExistByName", reflect.TypeOf((*MockObjectTypeService)(nil).CheckObjectTypeExistByName), ctx, knID, otName)
}

// CreateObjectTypes mocks base method.
func (m *MockObjectTypeService) CreateObjectTypes(ctx context.Context, tx *sql.Tx, objectTypes []*interfaces.ObjectType, mode string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObjectTypes", ctx, tx, objectTypes, mode)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateObjectTypes indicates an expected call of CreateObjectTypes.
func (mr *MockObjectTypeServiceMockRecorder) CreateObjectTypes(ctx, tx, objectTypes, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObjectTypes", reflect.TypeOf((*MockObjectTypeService)(nil).CreateObjectTypes), ctx, tx, objectTypes, mode)
}

// DeleteObjectTypes mocks base method.
func (m *MockObjectTypeService) DeleteObjectTypes(ctx context.Context, tx *sql.Tx, knID string, otIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectTypes", ctx, tx, knID, otIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObjectTypes indicates an expected call of DeleteObjectTypes.
func (mr *MockObjectTypeServiceMockRecorder) DeleteObjectTypes(ctx, tx, knID, otIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectTypes", reflect.TypeOf((*MockObjectTypeService)(nil).DeleteObjectTypes), ctx, tx, knID, otIDs)
}

// GetObjectTypeByID mocks base method.
func (m *MockObjectTypeService) GetObjectTypeByID(ctx context.Context, knID, otID string) (*interfaces.ObjectType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectTypeByID", ctx, knID, otID)
	ret0, _ := ret[0].(*interfaces.ObjectType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectTypeByID indicates an expected call of GetObjectTypeByID.
func (mr *MockObjectTypeServiceMockRecorder) GetObjectTypeByID(ctx, knID, otID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectTypeByID", reflect.TypeOf((*MockObjectTypeService)(nil).GetObjectTypeByID), ctx, knID, otID)
}

// GetObjectTypeIDsByKnID mocks base method.
func (m *MockObjectTypeService) GetObjectTypeIDsByKnID(ctx context.Context, knID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectTypeIDsByKnID", ctx, knID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectTypeIDsByKnID indicates an expected call of GetObjectTypeIDsByKnID.
func (mr *MockObjectTypeServiceMockRecorder) GetObjectTypeIDsByKnID(ctx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectTypeIDsByKnID", reflect.TypeOf((*MockObjectTypeService)(nil).GetObjectTypeIDsByKnID), ctx, knID)
}

// GetObjectTypes mocks base method.
func (m *MockObjectTypeService) GetObjectTypes(ctx context.Context, knID string, otIDs []string) ([]*interfaces.ObjectType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectTypes", ctx, knID, otIDs)
	ret0, _ := ret[0].([]*interfaces.ObjectType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectTypes indicates an expected call of GetObjectTypes.
func (mr *MockObjectTypeServiceMockRecorder) GetObjectTypes(ctx, knID, otIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectTypes", reflect.TypeOf((*MockObjectTypeService)(nil).GetObjectTypes), ctx, knID, otIDs)
}

// GetObjectTypesMapByIDs mocks base method.
func (m *MockObjectTypeService) GetObjectTypesMapByIDs(ctx context.Context, knID string, otIDs []string, needPropMap bool) (map[string]*interfaces.ObjectType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectTypesMapByIDs", ctx, knID, otIDs, needPropMap)
	ret0, _ := ret[0].(map[string]*interfaces.ObjectType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectTypesMapByIDs indicates an expected call of GetObjectTypesMapByIDs.
func (mr *MockObjectTypeServiceMockRecorder) GetObjectTypesMapByIDs(ctx, knID, otIDs, needPropMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectTypesMapByIDs", reflect.TypeOf((*MockObjectTypeService)(nil).GetObjectTypesMapByIDs), ctx, knID, otIDs, needPropMap)
}

// GetSimpleObjectTypeByKnID mocks base method.
func (m *MockObjectTypeService) GetSimpleObjectTypeByKnID(ctx context.Context, knID string) ([]*interfaces.SimpleObjectType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimpleObjectTypeByKnID", ctx, knID)
	ret0, _ := ret[0].([]*interfaces.SimpleObjectType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimpleObjectTypeByKnID indicates an expected call of GetSimpleObjectTypeByKnID.
func (mr *MockObjectTypeServiceMockRecorder) GetSimpleObjectTypeByKnID(ctx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimpleObjectTypeByKnID", reflect.TypeOf((*MockObjectTypeService)(nil).GetSimpleObjectTypeByKnID), ctx, knID)
}

// ListObjectTypes mocks base method.
func (m *MockObjectTypeService) ListObjectTypes(ctx context.Context, query interfaces.ObjectTypesQueryParams) ([]*interfaces.ObjectType, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectTypes", ctx, query)
	ret0, _ := ret[0].([]*interfaces.ObjectType)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListObjectTypes indicates an expected call of ListObjectTypes.
func (mr *MockObjectTypeServiceMockRecorder) ListObjectTypes(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectTypes", reflect.TypeOf((*MockObjectTypeService)(nil).ListObjectTypes), ctx, query)
}

// SearchObjectTypes mocks base method.
func (m *MockObjectTypeService) SearchObjectTypes(ctx context.Context, query *interfaces.ConceptsQuery) (interfaces.ObjectTypes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchObjectTypes", ctx, query)
	ret0, _ := ret[0].(interfaces.ObjectTypes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchObjectTypes indicates an expected call of SearchObjectTypes.
func (mr *MockObjectTypeServiceMockRecorder) SearchObjectTypes(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchObjectTypes", reflect.TypeOf((*MockObjectTypeService)(nil).SearchObjectTypes), ctx, query)
}

// UpdateDataProperties mocks base method.
func (m *MockObjectTypeService) UpdateDataProperties(ctx context.Context, objectType *interfaces.ObjectType, dataProperties []*interfaces.DataProperty) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataProperties", ctx, objectType, dataProperties)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDataProperties indicates an expected call of UpdateDataProperties.
func (mr *MockObjectTypeServiceMockRecorder) UpdateDataProperties(ctx, objectType, dataProperties interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataProperties", reflect.TypeOf((*MockObjectTypeService)(nil).UpdateDataProperties), ctx, objectType, dataProperties)
}

// UpdateObjectType mocks base method.
func (m *MockObjectTypeService) UpdateObjectType(ctx context.Context, tx *sql.Tx, objectType *interfaces.ObjectType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateObjectType", ctx, tx, objectType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateObjectType indicates an expected call of UpdateObjectType.
func (mr *MockObjectTypeServiceMockRecorder) UpdateObjectType(ctx, tx, objectType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateObjectType", reflect.TypeOf((*MockObjectTypeService)(nil).UpdateObjectType), ctx, tx, objectType)
}
