// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/knowledge_network_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockKNService is a mock of KNService interface.
type MockKNService struct {
	ctrl     *gomock.Controller
	recorder *MockKNServiceMockRecorder
}

// MockKNServiceMockRecorder is the mock recorder for MockKNService.
type MockKNServiceMockRecorder struct {
	mock *MockKNService
}

// NewMockKNService creates a new mock instance.
func NewMockKNService(ctrl *gomock.Controller) *MockKNService {
	mock := &MockKNService{ctrl: ctrl}
	mock.recorder = &MockKNServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKNService) EXPECT() *MockKNServiceMockRecorder {
	return m.recorder
}

// CheckKNExistByID mocks base method.
func (m *MockKNService) CheckKNExistByID(ctx context.Context, knID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckKNExistByID", ctx, knID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckKNExistByID indicates an expected call of CheckKNExistByID.
func (mr *MockKNServiceMockRecorder) CheckKNExistByID(ctx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckKNExistByID", reflect.TypeOf((*MockKNService)(nil).CheckKNExistByID), ctx, knID)
}

// CheckKNExistByName mocks base method.
func (m *MockKNService) CheckKNExistByName(ctx context.Context, knName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckKNExistByName", ctx, knName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckKNExistByName indicates an expected call of CheckKNExistByName.
func (mr *MockKNServiceMockRecorder) CheckKNExistByName(ctx, knName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckKNExistByName", reflect.TypeOf((*MockKNService)(nil).CheckKNExistByName), ctx, knName)
}

// CreateKN mocks base method.
func (m *MockKNService) CreateKN(ctx context.Context, kn *interfaces.KN, mode string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKN", ctx, kn, mode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKN indicates an expected call of CreateKN.
func (mr *MockKNServiceMockRecorder) CreateKN(ctx, kn, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKN", reflect.TypeOf((*MockKNService)(nil).CreateKN), ctx, kn, mode)
}

// DeleteKN mocks base method.
func (m *MockKNService) DeleteKN(ctx context.Context, knID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKN", ctx, knID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteKN indicates an expected call of DeleteKN.
func (mr *MockKNServiceMockRecorder) DeleteKN(ctx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKN", reflect.TypeOf((*MockKNService)(nil).DeleteKN), ctx, knID)
}

// GetKN mocks base method.
func (m *MockKNService) GetKN(ctx context.Context, knID, mode string) (*interfaces.KN, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKN", ctx, knID, mode)
	ret0, _ := ret[0].(*interfaces.KN)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKN indicates an expected call of GetKN.
func (mr *MockKNServiceMockRecorder) GetKN(ctx, knID, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKN", reflect.TypeOf((*MockKNService)(nil).GetKN), ctx, knID, mode)
}

// GetRelationTypePaths mocks base method.
func (m *MockKNService) GetRelationTypePaths(ctx context.Context, query interfaces.RelationTypePathsBaseOnSource) ([]interfaces.RelationTypePath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationTypePaths", ctx, query)
	ret0, _ := ret[0].([]interfaces.RelationTypePath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationTypePaths indicates an expected call of GetRelationTypePaths.
func (mr *MockKNServiceMockRecorder) GetRelationTypePaths(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationTypePaths", reflect.TypeOf((*MockKNService)(nil).GetRelationTypePaths), ctx, query)
}

// ListKNs mocks base method.
func (m *MockKNService) ListKNs(ctx context.Context, query interfaces.KNsQueryParams) ([]*interfaces.KN, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKNs", ctx, query)
	ret0, _ := ret[0].([]*interfaces.KN)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListKNs indicates an expected call of ListKNs.
func (mr *MockKNServiceMockRecorder) ListKNs(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKNs", reflect.TypeOf((*MockKNService)(nil).ListKNs), ctx, query)
}

// UpdateKN mocks base method.
func (m *MockKNService) UpdateKN(ctx context.Context, tx *sql.Tx, kn *interfaces.KN) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKN", ctx, tx, kn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKN indicates an expected call of UpdateKN.
func (mr *MockKNServiceMockRecorder) UpdateKN(ctx, tx, kn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKN", reflect.TypeOf((*MockKNService)(nil).UpdateKN), ctx, tx, kn)
}

// UpdateKNDetail mocks base method.
func (m *MockKNService) UpdateKNDetail(ctx context.Context, knID, detail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKNDetail", ctx, knID, detail)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKNDetail indicates an expected call of UpdateKNDetail.
func (mr *MockKNServiceMockRecorder) UpdateKNDetail(ctx, knID, detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKNDetail", reflect.TypeOf((*MockKNService)(nil).UpdateKNDetail), ctx, knID, detail)
}
