// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/action_type_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockActionTypeService is a mock of ActionTypeService interface.
type MockActionTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockActionTypeServiceMockRecorder
}

// MockActionTypeServiceMockRecorder is the mock recorder for MockActionTypeService.
type MockActionTypeServiceMockRecorder struct {
	mock *MockActionTypeService
}

// NewMockActionTypeService creates a new mock instance.
func NewMockActionTypeService(ctrl *gomock.Controller) *MockActionTypeService {
	mock := &MockActionTypeService{ctrl: ctrl}
	mock.recorder = &MockActionTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionTypeService) EXPECT() *MockActionTypeServiceMockRecorder {
	return m.recorder
}

// CheckActionTypeExistByID mocks base method.
func (m *MockActionTypeService) CheckActionTypeExistByID(ctx context.Context, knID, atID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckActionTypeExistByID", ctx, knID, atID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckActionTypeExistByID indicates an expected call of CheckActionTypeExistByID.
func (mr *MockActionTypeServiceMockRecorder) CheckActionTypeExistByID(ctx, knID, atID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckActionTypeExistByID", reflect.TypeOf((*MockActionTypeService)(nil).CheckActionTypeExistByID), ctx, knID, atID)
}

// CheckActionTypeExistByName mocks base method.
func (m *MockActionTypeService) CheckActionTypeExistByName(ctx context.Context, knID, atName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckActionTypeExistByName", ctx, knID, atName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckActionTypeExistByName indicates an expected call of CheckActionTypeExistByName.
func (mr *MockActionTypeServiceMockRecorder) CheckActionTypeExistByName(ctx, knID, atName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckActionTypeExistByName", reflect.TypeOf((*MockActionTypeService)(nil).CheckActionTypeExistByName), ctx, knID, atName)
}

// CreateActionTypes mocks base method.
func (m *MockActionTypeService) CreateActionTypes(ctx context.Context, tx *sql.Tx, actionTypes []*interfaces.ActionType, mode string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActionTypes", ctx, tx, actionTypes, mode)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActionTypes indicates an expected call of CreateActionTypes.
func (mr *MockActionTypeServiceMockRecorder) CreateActionTypes(ctx, tx, actionTypes, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActionTypes", reflect.TypeOf((*MockActionTypeService)(nil).CreateActionTypes), ctx, tx, actionTypes, mode)
}

// DeleteActionTypes mocks base method.
func (m *MockActionTypeService) DeleteActionTypes(ctx context.Context, tx *sql.Tx, knID string, atIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActionTypes", ctx, tx, knID, atIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteActionTypes indicates an expected call of DeleteActionTypes.
func (mr *MockActionTypeServiceMockRecorder) DeleteActionTypes(ctx, tx, knID, atIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActionTypes", reflect.TypeOf((*MockActionTypeService)(nil).DeleteActionTypes), ctx, tx, knID, atIDs)
}

// GetActionTypeIDsByKnID mocks base method.
func (m *MockActionTypeService) GetActionTypeIDsByKnID(ctx context.Context, knID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionTypeIDsByKnID", ctx, knID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActionTypeIDsByKnID indicates an expected call of GetActionTypeIDsByKnID.
func (mr *MockActionTypeServiceMockRecorder) GetActionTypeIDsByKnID(ctx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionTypeIDsByKnID", reflect.TypeOf((*MockActionTypeService)(nil).GetActionTypeIDsByKnID), ctx, knID)
}

// GetActionTypes mocks base method.
func (m *MockActionTypeService) GetActionTypes(ctx context.Context, knID string, atIDs []string) ([]*interfaces.ActionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionTypes", ctx, knID, atIDs)
	ret0, _ := ret[0].([]*interfaces.ActionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActionTypes indicates an expected call of GetActionTypes.
func (mr *MockActionTypeServiceMockRecorder) GetActionTypes(ctx, knID, atIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionTypes", reflect.TypeOf((*MockActionTypeService)(nil).GetActionTypes), ctx, knID, atIDs)
}

// ListActionTypes mocks base method.
func (m *MockActionTypeService) ListActionTypes(ctx context.Context, query interfaces.ActionTypesQueryParams) ([]*interfaces.ActionType, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActionTypes", ctx, query)
	ret0, _ := ret[0].([]*interfaces.ActionType)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListActionTypes indicates an expected call of ListActionTypes.
func (mr *MockActionTypeServiceMockRecorder) ListActionTypes(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActionTypes", reflect.TypeOf((*MockActionTypeService)(nil).ListActionTypes), ctx, query)
}

// SearchActionTypes mocks base method.
func (m *MockActionTypeService) SearchActionTypes(ctx context.Context, query *interfaces.ConceptsQuery) (interfaces.ActionTypes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchActionTypes", ctx, query)
	ret0, _ := ret[0].(interfaces.ActionTypes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchActionTypes indicates an expected call of SearchActionTypes.
func (mr *MockActionTypeServiceMockRecorder) SearchActionTypes(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchActionTypes", reflect.TypeOf((*MockActionTypeService)(nil).SearchActionTypes), ctx, query)
}

// UpdateActionType mocks base method.
func (m *MockActionTypeService) UpdateActionType(ctx context.Context, tx *sql.Tx, actionType *interfaces.ActionType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActionType", ctx, tx, actionType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActionType indicates an expected call of UpdateActionType.
func (mr *MockActionTypeServiceMockRecorder) UpdateActionType(ctx, tx, actionType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActionType", reflect.TypeOf((*MockActionTypeService)(nil).UpdateActionType), ctx, tx, actionType)
}
