// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/job_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJobService is a mock of JobService interface.
type MockJobService struct {
	ctrl     *gomock.Controller
	recorder *MockJobServiceMockRecorder
}

// MockJobServiceMockRecorder is the mock recorder for MockJobService.
type MockJobServiceMockRecorder struct {
	mock *MockJobService
}

// NewMockJobService creates a new mock instance.
func NewMockJobService(ctrl *gomock.Controller) *MockJobService {
	mock := &MockJobService{ctrl: ctrl}
	mock.recorder = &MockJobServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobService) EXPECT() *MockJobServiceMockRecorder {
	return m.recorder
}

// CreateJob mocks base method.
func (m *MockJobService) CreateJob(ctx context.Context, knID string, job *interfaces.Job) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", ctx, knID, job)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockJobServiceMockRecorder) CreateJob(ctx, knID, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockJobService)(nil).CreateJob), ctx, knID, job)
}

// DeleteJobs mocks base method.
func (m *MockJobService) DeleteJobs(ctx context.Context, knID string, jobIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJobs", ctx, knID, jobIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJobs indicates an expected call of DeleteJobs.
func (mr *MockJobServiceMockRecorder) DeleteJobs(ctx, knID, jobIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobs", reflect.TypeOf((*MockJobService)(nil).DeleteJobs), ctx, knID, jobIDs)
}

// GetJob mocks base method.
func (m *MockJobService) GetJob(ctx context.Context, jobID string) (*interfaces.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, jobID)
	ret0, _ := ret[0].(*interfaces.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockJobServiceMockRecorder) GetJob(ctx, jobID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockJobService)(nil).GetJob), ctx, jobID)
}

// GetJobs mocks base method.
func (m *MockJobService) GetJobs(ctx context.Context, jobIDs []string) (map[string]*interfaces.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobs", ctx, jobIDs)
	ret0, _ := ret[0].(map[string]*interfaces.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobs indicates an expected call of GetJobs.
func (mr *MockJobServiceMockRecorder) GetJobs(ctx, jobIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobs", reflect.TypeOf((*MockJobService)(nil).GetJobs), ctx, jobIDs)
}

// ListJobs mocks base method.
func (m *MockJobService) ListJobs(ctx context.Context, knID string, queryParams interfaces.JobsQueryParams) ([]*interfaces.Job, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobs", ctx, knID, queryParams)
	ret0, _ := ret[0].([]*interfaces.Job)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockJobServiceMockRecorder) ListJobs(ctx, knID, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockJobService)(nil).ListJobs), ctx, knID, queryParams)
}

// ListTasks mocks base method.
func (m *MockJobService) ListTasks(ctx context.Context, knID string, queryParams interfaces.TasksQueryParams) ([]*interfaces.Task, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", ctx, knID, queryParams)
	ret0, _ := ret[0].([]*interfaces.Task)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockJobServiceMockRecorder) ListTasks(ctx, knID, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockJobService)(nil).ListTasks), ctx, knID, queryParams)
}
