// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/opensearch_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOpenSearchAccess is a mock of OpenSearchAccess interface.
type MockOpenSearchAccess struct {
	ctrl     *gomock.Controller
	recorder *MockOpenSearchAccessMockRecorder
}

// MockOpenSearchAccessMockRecorder is the mock recorder for MockOpenSearchAccess.
type MockOpenSearchAccessMockRecorder struct {
	mock *MockOpenSearchAccess
}

// NewMockOpenSearchAccess creates a new mock instance.
func NewMockOpenSearchAccess(ctrl *gomock.Controller) *MockOpenSearchAccess {
	mock := &MockOpenSearchAccess{ctrl: ctrl}
	mock.recorder = &MockOpenSearchAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenSearchAccess) EXPECT() *MockOpenSearchAccessMockRecorder {
	return m.recorder
}

// BulkDeleteData mocks base method.
func (m *MockOpenSearchAccess) BulkDeleteData(ctx context.Context, indexName string, docIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkDeleteData", ctx, indexName, docIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkDeleteData indicates an expected call of BulkDeleteData.
func (mr *MockOpenSearchAccessMockRecorder) BulkDeleteData(ctx, indexName, docIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkDeleteData", reflect.TypeOf((*MockOpenSearchAccess)(nil).BulkDeleteData), ctx, indexName, docIDs)
}

// BulkInsertData mocks base method.
func (m *MockOpenSearchAccess) BulkInsertData(ctx context.Context, indexName string, dataList []any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertData", ctx, indexName, dataList)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsertData indicates an expected call of BulkInsertData.
func (mr *MockOpenSearchAccessMockRecorder) BulkInsertData(ctx, indexName, dataList interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertData", reflect.TypeOf((*MockOpenSearchAccess)(nil).BulkInsertData), ctx, indexName, dataList)
}

// Count mocks base method.
func (m *MockOpenSearchAccess) Count(ctx context.Context, indexName string, query any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, indexName, query)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockOpenSearchAccessMockRecorder) Count(ctx, indexName, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockOpenSearchAccess)(nil).Count), ctx, indexName, query)
}

// CreateIndex mocks base method.
func (m *MockOpenSearchAccess) CreateIndex(ctx context.Context, indexName string, body any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndex", ctx, indexName, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIndex indicates an expected call of CreateIndex.
func (mr *MockOpenSearchAccessMockRecorder) CreateIndex(ctx, indexName, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndex", reflect.TypeOf((*MockOpenSearchAccess)(nil).CreateIndex), ctx, indexName, body)
}

// DeleteData mocks base method.
func (m *MockOpenSearchAccess) DeleteData(ctx context.Context, indexName, docID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteData", ctx, indexName, docID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteData indicates an expected call of DeleteData.
func (mr *MockOpenSearchAccessMockRecorder) DeleteData(ctx, indexName, docID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteData", reflect.TypeOf((*MockOpenSearchAccess)(nil).DeleteData), ctx, indexName, docID)
}

// DeleteIndex mocks base method.
func (m *MockOpenSearchAccess) DeleteIndex(ctx context.Context, indexName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIndex", ctx, indexName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIndex indicates an expected call of DeleteIndex.
func (mr *MockOpenSearchAccessMockRecorder) DeleteIndex(ctx, indexName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIndex", reflect.TypeOf((*MockOpenSearchAccess)(nil).DeleteIndex), ctx, indexName)
}

// IndexExists mocks base method.
func (m *MockOpenSearchAccess) IndexExists(ctx context.Context, indexName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexExists", ctx, indexName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IndexExists indicates an expected call of IndexExists.
func (mr *MockOpenSearchAccessMockRecorder) IndexExists(ctx, indexName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexExists", reflect.TypeOf((*MockOpenSearchAccess)(nil).IndexExists), ctx, indexName)
}

// InsertData mocks base method.
func (m *MockOpenSearchAccess) InsertData(ctx context.Context, indexName, docID string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertData", ctx, indexName, docID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertData indicates an expected call of InsertData.
func (mr *MockOpenSearchAccessMockRecorder) InsertData(ctx, indexName, docID, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertData", reflect.TypeOf((*MockOpenSearchAccess)(nil).InsertData), ctx, indexName, docID, data)
}

// SearchData mocks base method.
func (m *MockOpenSearchAccess) SearchData(ctx context.Context, indexName string, query any) ([]interfaces.Hit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchData", ctx, indexName, query)
	ret0, _ := ret[0].([]interfaces.Hit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchData indicates an expected call of SearchData.
func (mr *MockOpenSearchAccessMockRecorder) SearchData(ctx, indexName, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchData", reflect.TypeOf((*MockOpenSearchAccess)(nil).SearchData), ctx, indexName, query)
}
