// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/data_view_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataViewAccess is a mock of DataViewAccess interface.
type MockDataViewAccess struct {
	ctrl     *gomock.Controller
	recorder *MockDataViewAccessMockRecorder
}

// MockDataViewAccessMockRecorder is the mock recorder for MockDataViewAccess.
type MockDataViewAccessMockRecorder struct {
	mock *MockDataViewAccess
}

// NewMockDataViewAccess creates a new mock instance.
func NewMockDataViewAccess(ctrl *gomock.Controller) *MockDataViewAccess {
	mock := &MockDataViewAccess{ctrl: ctrl}
	mock.recorder = &MockDataViewAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataViewAccess) EXPECT() *MockDataViewAccessMockRecorder {
	return m.recorder
}

// GetDataNext mocks base method.
func (m *MockDataViewAccess) GetDataNext(ctx context.Context, id string, searchAfter []any) (*interfaces.ViewQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataNext", ctx, id, searchAfter)
	ret0, _ := ret[0].(*interfaces.ViewQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataNext indicates an expected call of GetDataNext.
func (mr *MockDataViewAccessMockRecorder) GetDataNext(ctx, id, searchAfter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataNext", reflect.TypeOf((*MockDataViewAccess)(nil).GetDataNext), ctx, id, searchAfter)
}

// GetDataStart mocks base method.
func (m *MockDataViewAccess) GetDataStart(ctx context.Context, id string) (*interfaces.ViewQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataStart", ctx, id)
	ret0, _ := ret[0].(*interfaces.ViewQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataStart indicates an expected call of GetDataStart.
func (mr *MockDataViewAccessMockRecorder) GetDataStart(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataStart", reflect.TypeOf((*MockDataViewAccess)(nil).GetDataStart), ctx, id)
}

// GetDataViewByID mocks base method.
func (m *MockDataViewAccess) GetDataViewByID(ctx context.Context, id string) (*interfaces.DataView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataViewByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.DataView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataViewByID indicates an expected call of GetDataViewByID.
func (mr *MockDataViewAccessMockRecorder) GetDataViewByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataViewByID", reflect.TypeOf((*MockDataViewAccess)(nil).GetDataViewByID), ctx, id)
}
