// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/object_type_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockObjectTypeAccess is a mock of ObjectTypeAccess interface.
type MockObjectTypeAccess struct {
	ctrl     *gomock.Controller
	recorder *MockObjectTypeAccessMockRecorder
}

// MockObjectTypeAccessMockRecorder is the mock recorder for MockObjectTypeAccess.
type MockObjectTypeAccessMockRecorder struct {
	mock *MockObjectTypeAccess
}

// NewMockObjectTypeAccess creates a new mock instance.
func NewMockObjectTypeAccess(ctrl *gomock.Controller) *MockObjectTypeAccess {
	mock := &MockObjectTypeAccess{ctrl: ctrl}
	mock.recorder = &MockObjectTypeAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectTypeAccess) EXPECT() *MockObjectTypeAccessMockRecorder {
	return m.recorder
}

// CheckObjectTypeExistByID mocks base method.
func (m *MockObjectTypeAccess) CheckObjectTypeExistByID(ctx context.Context, knID, otID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckObjectTypeExistByID", ctx, knID, otID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckObjectTypeExistByID indicates an expected call of CheckObjectTypeExistByID.
func (mr *MockObjectTypeAccessMockRecorder) CheckObjectTypeExistByID(ctx, knID, otID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckObjectTypeExistByID", reflect.TypeOf((*MockObjectTypeAccess)(nil).CheckObjectTypeExistByID), ctx, knID, otID)
}

// CheckObjectTypeExistByName mocks base method.
func (m *MockObjectTypeAccess) CheckObjectTypeExistByName(ctx context.Context, knID, otName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckObjectTypeExistByName", ctx, knID, otName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckObjectTypeExistByName indicates an expected call of CheckObjectTypeExistByName.
func (mr *MockObjectTypeAccessMockRecorder) CheckObjectTypeExistByName(ctx, knID, otName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckObjectTypeExistByName", reflect.TypeOf((*MockObjectTypeAccess)(nil).CheckObjectTypeExistByName), ctx, knID, otName)
}

// CreateObjectType mocks base method.
func (m *MockObjectTypeAccess) CreateObjectType(ctx context.Context, tx *sql.Tx, objectType *interfaces.ObjectType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObjectType", ctx, tx, objectType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateObjectType indicates an expected call of CreateObjectType.
func (mr *MockObjectTypeAccessMockRecorder) CreateObjectType(ctx, tx, objectType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObjectType", reflect.TypeOf((*MockObjectTypeAccess)(nil).CreateObjectType), ctx, tx, objectType)
}

// DeleteObjectTypes mocks base method.
func (m *MockObjectTypeAccess) DeleteObjectTypes(ctx context.Context, tx *sql.Tx, knID string, otIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectTypes", ctx, tx, knID, otIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObjectTypes indicates an expected call of DeleteObjectTypes.
func (mr *MockObjectTypeAccessMockRecorder) DeleteObjectTypes(ctx, tx, knID, otIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectTypes", reflect.TypeOf((*MockObjectTypeAccess)(nil).DeleteObjectTypes), ctx, tx, knID, otIDs)
}

// GetObjectTypeByID mocks base method.
func (m *MockObjectTypeAccess) GetObjectTypeByID(ctx context.Context, knID, otID string) (*interfaces.ObjectType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectTypeByID", ctx, knID, otID)
	ret0, _ := ret[0].(*interfaces.ObjectType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectTypeByID indicates an expected call of GetObjectTypeByID.
func (mr *MockObjectTypeAccessMockRecorder) GetObjectTypeByID(ctx, knID, otID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectTypeByID", reflect.TypeOf((*MockObjectTypeAccess)(nil).GetObjectTypeByID), ctx, knID, otID)
}

// GetObjectTypeIDsByKnID mocks base method.
func (m *MockObjectTypeAccess) GetObjectTypeIDsByKnID(ctx context.Context, knID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectTypeIDsByKnID", ctx, knID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectTypeIDsByKnID indicates an expected call of GetObjectTypeIDsByKnID.
func (mr *MockObjectTypeAccessMockRecorder) GetObjectTypeIDsByKnID(ctx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectTypeIDsByKnID", reflect.TypeOf((*MockObjectTypeAccess)(nil).GetObjectTypeIDsByKnID), ctx, knID)
}

// GetObjectTypesByIDs mocks base method.
func (m *MockObjectTypeAccess) GetObjectTypesByIDs(ctx context.Context, knID string, otIDs []string) ([]*interfaces.ObjectType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectTypesByIDs", ctx, knID, otIDs)
	ret0, _ := ret[0].([]*interfaces.ObjectType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectTypesByIDs indicates an expected call of GetObjectTypesByIDs.
func (mr *MockObjectTypeAccessMockRecorder) GetObjectTypesByIDs(ctx, knID, otIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectTypesByIDs", reflect.TypeOf((*MockObjectTypeAccess)(nil).GetObjectTypesByIDs), ctx, knID, otIDs)
}

// GetObjectTypesTotal mocks base method.
func (m *MockObjectTypeAccess) GetObjectTypesTotal(ctx context.Context, query interfaces.ObjectTypesQueryParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectTypesTotal", ctx, query)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectTypesTotal indicates an expected call of GetObjectTypesTotal.
func (mr *MockObjectTypeAccessMockRecorder) GetObjectTypesTotal(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectTypesTotal", reflect.TypeOf((*MockObjectTypeAccess)(nil).GetObjectTypesTotal), ctx, query)
}

// GetSimpleObjectTypeByKnID mocks base method.
func (m *MockObjectTypeAccess) GetSimpleObjectTypeByKnID(ctx context.Context, knID string) ([]*interfaces.SimpleObjectType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimpleObjectTypeByKnID", ctx, knID)
	ret0, _ := ret[0].([]*interfaces.SimpleObjectType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimpleObjectTypeByKnID indicates an expected call of GetSimpleObjectTypeByKnID.
func (mr *MockObjectTypeAccessMockRecorder) GetSimpleObjectTypeByKnID(ctx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimpleObjectTypeByKnID", reflect.TypeOf((*MockObjectTypeAccess)(nil).GetSimpleObjectTypeByKnID), ctx, knID)
}

// ListObjectTypes mocks base method.
func (m *MockObjectTypeAccess) ListObjectTypes(ctx context.Context, query interfaces.ObjectTypesQueryParams) ([]*interfaces.ObjectType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectTypes", ctx, query)
	ret0, _ := ret[0].([]*interfaces.ObjectType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectTypes indicates an expected call of ListObjectTypes.
func (mr *MockObjectTypeAccessMockRecorder) ListObjectTypes(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectTypes", reflect.TypeOf((*MockObjectTypeAccess)(nil).ListObjectTypes), ctx, query)
}

// UpdateDataProperties mocks base method.
func (m *MockObjectTypeAccess) UpdateDataProperties(ctx context.Context, objectType *interfaces.ObjectType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataProperties", ctx, objectType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDataProperties indicates an expected call of UpdateDataProperties.
func (mr *MockObjectTypeAccessMockRecorder) UpdateDataProperties(ctx, objectType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataProperties", reflect.TypeOf((*MockObjectTypeAccess)(nil).UpdateDataProperties), ctx, objectType)
}

// UpdateObjectType mocks base method.
func (m *MockObjectTypeAccess) UpdateObjectType(ctx context.Context, tx *sql.Tx, objectType *interfaces.ObjectType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateObjectType", ctx, tx, objectType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateObjectType indicates an expected call of UpdateObjectType.
func (mr *MockObjectTypeAccessMockRecorder) UpdateObjectType(ctx, tx, objectType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateObjectType", reflect.TypeOf((*MockObjectTypeAccess)(nil).UpdateObjectType), ctx, tx, objectType)
}

// UpdateObjectTypeIndex mocks base method.
func (m *MockObjectTypeAccess) UpdateObjectTypeIndex(ctx context.Context, tx *sql.Tx, knID, otID, index string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateObjectTypeIndex", ctx, tx, knID, otID, index)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateObjectTypeIndex indicates an expected call of UpdateObjectTypeIndex.
func (mr *MockObjectTypeAccessMockRecorder) UpdateObjectTypeIndex(ctx, tx, knID, otID, index interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateObjectTypeIndex", reflect.TypeOf((*MockObjectTypeAccess)(nil).UpdateObjectTypeIndex), ctx, tx, knID, otID, index)
}
