// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/action_type_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockActionTypeAccess is a mock of ActionTypeAccess interface.
type MockActionTypeAccess struct {
	ctrl     *gomock.Controller
	recorder *MockActionTypeAccessMockRecorder
}

// MockActionTypeAccessMockRecorder is the mock recorder for MockActionTypeAccess.
type MockActionTypeAccessMockRecorder struct {
	mock *MockActionTypeAccess
}

// NewMockActionTypeAccess creates a new mock instance.
func NewMockActionTypeAccess(ctrl *gomock.Controller) *MockActionTypeAccess {
	mock := &MockActionTypeAccess{ctrl: ctrl}
	mock.recorder = &MockActionTypeAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionTypeAccess) EXPECT() *MockActionTypeAccessMockRecorder {
	return m.recorder
}

// CheckActionTypeExistByID mocks base method.
func (m *MockActionTypeAccess) CheckActionTypeExistByID(ctx context.Context, knID, atID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckActionTypeExistByID", ctx, knID, atID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckActionTypeExistByID indicates an expected call of CheckActionTypeExistByID.
func (mr *MockActionTypeAccessMockRecorder) CheckActionTypeExistByID(ctx, knID, atID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckActionTypeExistByID", reflect.TypeOf((*MockActionTypeAccess)(nil).CheckActionTypeExistByID), ctx, knID, atID)
}

// CheckActionTypeExistByName mocks base method.
func (m *MockActionTypeAccess) CheckActionTypeExistByName(ctx context.Context, knID, atName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckActionTypeExistByName", ctx, knID, atName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckActionTypeExistByName indicates an expected call of CheckActionTypeExistByName.
func (mr *MockActionTypeAccessMockRecorder) CheckActionTypeExistByName(ctx, knID, atName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckActionTypeExistByName", reflect.TypeOf((*MockActionTypeAccess)(nil).CheckActionTypeExistByName), ctx, knID, atName)
}

// CreateActionType mocks base method.
func (m *MockActionTypeAccess) CreateActionType(ctx context.Context, tx *sql.Tx, actionType *interfaces.ActionType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActionType", ctx, tx, actionType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateActionType indicates an expected call of CreateActionType.
func (mr *MockActionTypeAccessMockRecorder) CreateActionType(ctx, tx, actionType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActionType", reflect.TypeOf((*MockActionTypeAccess)(nil).CreateActionType), ctx, tx, actionType)
}

// DeleteActionTypes mocks base method.
func (m *MockActionTypeAccess) DeleteActionTypes(ctx context.Context, tx *sql.Tx, knID string, atIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActionTypes", ctx, tx, knID, atIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteActionTypes indicates an expected call of DeleteActionTypes.
func (mr *MockActionTypeAccessMockRecorder) DeleteActionTypes(ctx, tx, knID, atIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActionTypes", reflect.TypeOf((*MockActionTypeAccess)(nil).DeleteActionTypes), ctx, tx, knID, atIDs)
}

// GetActionTypeIDsByKnID mocks base method.
func (m *MockActionTypeAccess) GetActionTypeIDsByKnID(ctx context.Context, knID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionTypeIDsByKnID", ctx, knID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActionTypeIDsByKnID indicates an expected call of GetActionTypeIDsByKnID.
func (mr *MockActionTypeAccessMockRecorder) GetActionTypeIDsByKnID(ctx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionTypeIDsByKnID", reflect.TypeOf((*MockActionTypeAccess)(nil).GetActionTypeIDsByKnID), ctx, knID)
}

// GetActionTypesByIDs mocks base method.
func (m *MockActionTypeAccess) GetActionTypesByIDs(ctx context.Context, knID string, atIDs []string) ([]*interfaces.ActionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionTypesByIDs", ctx, knID, atIDs)
	ret0, _ := ret[0].([]*interfaces.ActionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActionTypesByIDs indicates an expected call of GetActionTypesByIDs.
func (mr *MockActionTypeAccessMockRecorder) GetActionTypesByIDs(ctx, knID, atIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionTypesByIDs", reflect.TypeOf((*MockActionTypeAccess)(nil).GetActionTypesByIDs), ctx, knID, atIDs)
}

// GetActionTypesTotal mocks base method.
func (m *MockActionTypeAccess) GetActionTypesTotal(ctx context.Context, query interfaces.ActionTypesQueryParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionTypesTotal", ctx, query)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActionTypesTotal indicates an expected call of GetActionTypesTotal.
func (mr *MockActionTypeAccessMockRecorder) GetActionTypesTotal(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionTypesTotal", reflect.TypeOf((*MockActionTypeAccess)(nil).GetActionTypesTotal), ctx, query)
}

// ListActionTypes mocks base method.
func (m *MockActionTypeAccess) ListActionTypes(ctx context.Context, query interfaces.ActionTypesQueryParams) ([]*interfaces.ActionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActionTypes", ctx, query)
	ret0, _ := ret[0].([]*interfaces.ActionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActionTypes indicates an expected call of ListActionTypes.
func (mr *MockActionTypeAccessMockRecorder) ListActionTypes(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActionTypes", reflect.TypeOf((*MockActionTypeAccess)(nil).ListActionTypes), ctx, query)
}

// UpdateActionType mocks base method.
func (m *MockActionTypeAccess) UpdateActionType(ctx context.Context, tx *sql.Tx, actionType *interfaces.ActionType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActionType", ctx, tx, actionType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActionType indicates an expected call of UpdateActionType.
func (mr *MockActionTypeAccessMockRecorder) UpdateActionType(ctx, tx, actionType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActionType", reflect.TypeOf((*MockActionTypeAccess)(nil).UpdateActionType), ctx, tx, actionType)
}
