// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/model_factory_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	condition "ontology-manager/common/condition"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockModelFactoryAccess is a mock of ModelFactoryAccess interface.
type MockModelFactoryAccess struct {
	ctrl     *gomock.Controller
	recorder *MockModelFactoryAccessMockRecorder
}

// MockModelFactoryAccessMockRecorder is the mock recorder for MockModelFactoryAccess.
type MockModelFactoryAccessMockRecorder struct {
	mock *MockModelFactoryAccess
}

// NewMockModelFactoryAccess creates a new mock instance.
func NewMockModelFactoryAccess(ctrl *gomock.Controller) *MockModelFactoryAccess {
	mock := &MockModelFactoryAccess{ctrl: ctrl}
	mock.recorder = &MockModelFactoryAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelFactoryAccess) EXPECT() *MockModelFactoryAccessMockRecorder {
	return m.recorder
}

// GetModelByID mocks base method.
func (m *MockModelFactoryAccess) GetModelByID(ctx context.Context, modelID string) (*interfaces.SmallModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelByID", ctx, modelID)
	ret0, _ := ret[0].(*interfaces.SmallModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelByID indicates an expected call of GetModelByID.
func (mr *MockModelFactoryAccessMockRecorder) GetModelByID(ctx, modelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelByID", reflect.TypeOf((*MockModelFactoryAccess)(nil).GetModelByID), ctx, modelID)
}

// GetVector mocks base method.
func (m *MockModelFactoryAccess) GetVector(ctx context.Context, modelID string, words []string) ([]condition.VectorResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVector", ctx, modelID, words)
	ret0, _ := ret[0].([]condition.VectorResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVector indicates an expected call of GetVector.
func (mr *MockModelFactoryAccessMockRecorder) GetVector(ctx, modelID, words interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVector", reflect.TypeOf((*MockModelFactoryAccess)(nil).GetVector), ctx, modelID, words)
}
