// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/relation_type_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRelationTypeAccess is a mock of RelationTypeAccess interface.
type MockRelationTypeAccess struct {
	ctrl     *gomock.Controller
	recorder *MockRelationTypeAccessMockRecorder
}

// MockRelationTypeAccessMockRecorder is the mock recorder for MockRelationTypeAccess.
type MockRelationTypeAccessMockRecorder struct {
	mock *MockRelationTypeAccess
}

// NewMockRelationTypeAccess creates a new mock instance.
func NewMockRelationTypeAccess(ctrl *gomock.Controller) *MockRelationTypeAccess {
	mock := &MockRelationTypeAccess{ctrl: ctrl}
	mock.recorder = &MockRelationTypeAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelationTypeAccess) EXPECT() *MockRelationTypeAccessMockRecorder {
	return m.recorder
}

// CheckRelationTypeExistByID mocks base method.
func (m *MockRelationTypeAccess) CheckRelationTypeExistByID(ctx context.Context, knID, rtID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRelationTypeExistByID", ctx, knID, rtID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckRelationTypeExistByID indicates an expected call of CheckRelationTypeExistByID.
func (mr *MockRelationTypeAccessMockRecorder) CheckRelationTypeExistByID(ctx, knID, rtID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRelationTypeExistByID", reflect.TypeOf((*MockRelationTypeAccess)(nil).CheckRelationTypeExistByID), ctx, knID, rtID)
}

// CheckRelationTypeExistByName mocks base method.
func (m *MockRelationTypeAccess) CheckRelationTypeExistByName(ctx context.Context, knID, rtName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRelationTypeExistByName", ctx, knID, rtName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckRelationTypeExistByName indicates an expected call of CheckRelationTypeExistByName.
func (mr *MockRelationTypeAccessMockRecorder) CheckRelationTypeExistByName(ctx, knID, rtName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRelationTypeExistByName", reflect.TypeOf((*MockRelationTypeAccess)(nil).CheckRelationTypeExistByName), ctx, knID, rtName)
}

// CreateRelationType mocks base method.
func (m *MockRelationTypeAccess) CreateRelationType(ctx context.Context, tx *sql.Tx, relationType *interfaces.RelationType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRelationType", ctx, tx, relationType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRelationType indicates an expected call of CreateRelationType.
func (mr *MockRelationTypeAccessMockRecorder) CreateRelationType(ctx, tx, relationType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRelationType", reflect.TypeOf((*MockRelationTypeAccess)(nil).CreateRelationType), ctx, tx, relationType)
}

// DeleteRelationTypes mocks base method.
func (m *MockRelationTypeAccess) DeleteRelationTypes(ctx context.Context, tx *sql.Tx, knID string, rtIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRelationTypes", ctx, tx, knID, rtIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRelationTypes indicates an expected call of DeleteRelationTypes.
func (mr *MockRelationTypeAccessMockRecorder) DeleteRelationTypes(ctx, tx, knID, rtIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRelationTypes", reflect.TypeOf((*MockRelationTypeAccess)(nil).DeleteRelationTypes), ctx, tx, knID, rtIDs)
}

// GetRelationTypeByID mocks base method.
func (m *MockRelationTypeAccess) GetRelationTypeByID(ctx context.Context, knID, rtID string) (*interfaces.RelationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationTypeByID", ctx, knID, rtID)
	ret0, _ := ret[0].(*interfaces.RelationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationTypeByID indicates an expected call of GetRelationTypeByID.
func (mr *MockRelationTypeAccessMockRecorder) GetRelationTypeByID(ctx, knID, rtID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationTypeByID", reflect.TypeOf((*MockRelationTypeAccess)(nil).GetRelationTypeByID), ctx, knID, rtID)
}

// GetRelationTypeIDsByKnID mocks base method.
func (m *MockRelationTypeAccess) GetRelationTypeIDsByKnID(ctx context.Context, knID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationTypeIDsByKnID", ctx, knID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationTypeIDsByKnID indicates an expected call of GetRelationTypeIDsByKnID.
func (mr *MockRelationTypeAccessMockRecorder) GetRelationTypeIDsByKnID(ctx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationTypeIDsByKnID", reflect.TypeOf((*MockRelationTypeAccess)(nil).GetRelationTypeIDsByKnID), ctx, knID)
}

// GetRelationTypesByIDs mocks base method.
func (m *MockRelationTypeAccess) GetRelationTypesByIDs(ctx context.Context, knID string, rtIDs []string) ([]*interfaces.RelationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationTypesByIDs", ctx, knID, rtIDs)
	ret0, _ := ret[0].([]*interfaces.RelationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationTypesByIDs indicates an expected call of GetRelationTypesByIDs.
func (mr *MockRelationTypeAccessMockRecorder) GetRelationTypesByIDs(ctx, knID, rtIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationTypesByIDs", reflect.TypeOf((*MockRelationTypeAccess)(nil).GetRelationTypesByIDs), ctx, knID, rtIDs)
}

// GetRelationTypesTotal mocks base method.
func (m *MockRelationTypeAccess) GetRelationTypesTotal(ctx context.Context, query interfaces.RelationTypesQueryParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationTypesTotal", ctx, query)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationTypesTotal indicates an expected call of GetRelationTypesTotal.
func (mr *MockRelationTypeAccessMockRecorder) GetRelationTypesTotal(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationTypesTotal", reflect.TypeOf((*MockRelationTypeAccess)(nil).GetRelationTypesTotal), ctx, query)
}

// ListRelationTypes mocks base method.
func (m *MockRelationTypeAccess) ListRelationTypes(ctx context.Context, query interfaces.RelationTypesQueryParams) ([]*interfaces.RelationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRelationTypes", ctx, query)
	ret0, _ := ret[0].([]*interfaces.RelationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRelationTypes indicates an expected call of ListRelationTypes.
func (mr *MockRelationTypeAccessMockRecorder) ListRelationTypes(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRelationTypes", reflect.TypeOf((*MockRelationTypeAccess)(nil).ListRelationTypes), ctx, query)
}

// UpdateRelationType mocks base method.
func (m *MockRelationTypeAccess) UpdateRelationType(ctx context.Context, tx *sql.Tx, relationType *interfaces.RelationType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRelationType", ctx, tx, relationType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRelationType indicates an expected call of UpdateRelationType.
func (mr *MockRelationTypeAccessMockRecorder) UpdateRelationType(ctx, tx, relationType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRelationType", reflect.TypeOf((*MockRelationTypeAccess)(nil).UpdateRelationType), ctx, tx, relationType)
}
