// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/relation_type_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRelationTypeService is a mock of RelationTypeService interface.
type MockRelationTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockRelationTypeServiceMockRecorder
}

// MockRelationTypeServiceMockRecorder is the mock recorder for MockRelationTypeService.
type MockRelationTypeServiceMockRecorder struct {
	mock *MockRelationTypeService
}

// NewMockRelationTypeService creates a new mock instance.
func NewMockRelationTypeService(ctrl *gomock.Controller) *MockRelationTypeService {
	mock := &MockRelationTypeService{ctrl: ctrl}
	mock.recorder = &MockRelationTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelationTypeService) EXPECT() *MockRelationTypeServiceMockRecorder {
	return m.recorder
}

// CheckRelationTypeExistByID mocks base method.
func (m *MockRelationTypeService) CheckRelationTypeExistByID(ctx context.Context, knID, rtID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRelationTypeExistByID", ctx, knID, rtID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckRelationTypeExistByID indicates an expected call of CheckRelationTypeExistByID.
func (mr *MockRelationTypeServiceMockRecorder) CheckRelationTypeExistByID(ctx, knID, rtID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRelationTypeExistByID", reflect.TypeOf((*MockRelationTypeService)(nil).CheckRelationTypeExistByID), ctx, knID, rtID)
}

// CheckRelationTypeExistByName mocks base method.
func (m *MockRelationTypeService) CheckRelationTypeExistByName(ctx context.Context, knID, rtName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRelationTypeExistByName", ctx, knID, rtName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckRelationTypeExistByName indicates an expected call of CheckRelationTypeExistByName.
func (mr *MockRelationTypeServiceMockRecorder) CheckRelationTypeExistByName(ctx, knID, rtName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRelationTypeExistByName", reflect.TypeOf((*MockRelationTypeService)(nil).CheckRelationTypeExistByName), ctx, knID, rtName)
}

// CreateRelationTypes mocks base method.
func (m *MockRelationTypeService) CreateRelationTypes(ctx context.Context, tx *sql.Tx, relationTypes []*interfaces.RelationType, mode string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRelationTypes", ctx, tx, relationTypes, mode)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRelationTypes indicates an expected call of CreateRelationTypes.
func (mr *MockRelationTypeServiceMockRecorder) CreateRelationTypes(ctx, tx, relationTypes, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRelationTypes", reflect.TypeOf((*MockRelationTypeService)(nil).CreateRelationTypes), ctx, tx, relationTypes, mode)
}

// DeleteRelationTypes mocks base method.
func (m *MockRelationTypeService) DeleteRelationTypes(ctx context.Context, tx *sql.Tx, knID string, rtIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRelationTypes", ctx, tx, knID, rtIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRelationTypes indicates an expected call of DeleteRelationTypes.
func (mr *MockRelationTypeServiceMockRecorder) DeleteRelationTypes(ctx, tx, knID, rtIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRelationTypes", reflect.TypeOf((*MockRelationTypeService)(nil).DeleteRelationTypes), ctx, tx, knID, rtIDs)
}

// GetRelationTypeIDsByKnID mocks base method.
func (m *MockRelationTypeService) GetRelationTypeIDsByKnID(ctx context.Context, knID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationTypeIDsByKnID", ctx, knID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationTypeIDsByKnID indicates an expected call of GetRelationTypeIDsByKnID.
func (mr *MockRelationTypeServiceMockRecorder) GetRelationTypeIDsByKnID(ctx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationTypeIDsByKnID", reflect.TypeOf((*MockRelationTypeService)(nil).GetRelationTypeIDsByKnID), ctx, knID)
}

// GetRelationTypes mocks base method.
func (m *MockRelationTypeService) GetRelationTypes(ctx context.Context, knID string, rtIDs []string) ([]*interfaces.RelationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationTypes", ctx, knID, rtIDs)
	ret0, _ := ret[0].([]*interfaces.RelationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationTypes indicates an expected call of GetRelationTypes.
func (mr *MockRelationTypeServiceMockRecorder) GetRelationTypes(ctx, knID, rtIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationTypes", reflect.TypeOf((*MockRelationTypeService)(nil).GetRelationTypes), ctx, knID, rtIDs)
}

// ListRelationTypes mocks base method.
func (m *MockRelationTypeService) ListRelationTypes(ctx context.Context, query interfaces.RelationTypesQueryParams) ([]*interfaces.RelationType, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRelationTypes", ctx, query)
	ret0, _ := ret[0].([]*interfaces.RelationType)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRelationTypes indicates an expected call of ListRelationTypes.
func (mr *MockRelationTypeServiceMockRecorder) ListRelationTypes(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRelationTypes", reflect.TypeOf((*MockRelationTypeService)(nil).ListRelationTypes), ctx, query)
}

// SearchRelationTypes mocks base method.
func (m *MockRelationTypeService) SearchRelationTypes(ctx context.Context, query *interfaces.ConceptsQuery) (interfaces.RelationTypes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRelationTypes", ctx, query)
	ret0, _ := ret[0].(interfaces.RelationTypes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRelationTypes indicates an expected call of SearchRelationTypes.
func (mr *MockRelationTypeServiceMockRecorder) SearchRelationTypes(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRelationTypes", reflect.TypeOf((*MockRelationTypeService)(nil).SearchRelationTypes), ctx, query)
}

// UpdateRelationType mocks base method.
func (m *MockRelationTypeService) UpdateRelationType(ctx context.Context, tx *sql.Tx, relationType *interfaces.RelationType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRelationType", ctx, tx, relationType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRelationType indicates an expected call of UpdateRelationType.
func (mr *MockRelationTypeServiceMockRecorder) UpdateRelationType(ctx, tx, relationType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRelationType", reflect.TypeOf((*MockRelationTypeService)(nil).UpdateRelationType), ctx, tx, relationType)
}
