// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/job_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJobAccess is a mock of JobAccess interface.
type MockJobAccess struct {
	ctrl     *gomock.Controller
	recorder *MockJobAccessMockRecorder
}

// MockJobAccessMockRecorder is the mock recorder for MockJobAccess.
type MockJobAccessMockRecorder struct {
	mock *MockJobAccess
}

// NewMockJobAccess creates a new mock instance.
func NewMockJobAccess(ctrl *gomock.Controller) *MockJobAccess {
	mock := &MockJobAccess{ctrl: ctrl}
	mock.recorder = &MockJobAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobAccess) EXPECT() *MockJobAccessMockRecorder {
	return m.recorder
}

// CreateJob mocks base method.
func (m *MockJobAccess) CreateJob(ctx context.Context, tx *sql.Tx, job *interfaces.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", ctx, tx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockJobAccessMockRecorder) CreateJob(ctx, tx, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockJobAccess)(nil).CreateJob), ctx, tx, job)
}

// CreateTasks mocks base method.
func (m *MockJobAccess) CreateTasks(ctx context.Context, tx *sql.Tx, tasks map[string]*interfaces.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTasks", ctx, tx, tasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTasks indicates an expected call of CreateTasks.
func (mr *MockJobAccessMockRecorder) CreateTasks(ctx, tx, tasks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTasks", reflect.TypeOf((*MockJobAccess)(nil).CreateTasks), ctx, tx, tasks)
}

// DeleteJobs mocks base method.
func (m *MockJobAccess) DeleteJobs(ctx context.Context, tx *sql.Tx, jobIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJobs", ctx, tx, jobIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJobs indicates an expected call of DeleteJobs.
func (mr *MockJobAccessMockRecorder) DeleteJobs(ctx, tx, jobIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobs", reflect.TypeOf((*MockJobAccess)(nil).DeleteJobs), ctx, tx, jobIDs)
}

// DeleteTasks mocks base method.
func (m *MockJobAccess) DeleteTasks(ctx context.Context, tx *sql.Tx, jobIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTasks", ctx, tx, jobIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTasks indicates an expected call of DeleteTasks.
func (mr *MockJobAccessMockRecorder) DeleteTasks(ctx, tx, jobIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTasks", reflect.TypeOf((*MockJobAccess)(nil).DeleteTasks), ctx, tx, jobIDs)
}

// GetJob mocks base method.
func (m *MockJobAccess) GetJob(ctx context.Context, jobID string) (*interfaces.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, jobID)
	ret0, _ := ret[0].(*interfaces.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockJobAccessMockRecorder) GetJob(ctx, jobID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockJobAccess)(nil).GetJob), ctx, jobID)
}

// GetJobs mocks base method.
func (m *MockJobAccess) GetJobs(ctx context.Context, jobIDs []string) (map[string]*interfaces.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobs", ctx, jobIDs)
	ret0, _ := ret[0].(map[string]*interfaces.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobs indicates an expected call of GetJobs.
func (mr *MockJobAccessMockRecorder) GetJobs(ctx, jobIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobs", reflect.TypeOf((*MockJobAccess)(nil).GetJobs), ctx, jobIDs)
}

// GetJobsTotal mocks base method.
func (m *MockJobAccess) GetJobsTotal(ctx context.Context, queryParams interfaces.JobsQueryParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobsTotal", ctx, queryParams)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobsTotal indicates an expected call of GetJobsTotal.
func (mr *MockJobAccessMockRecorder) GetJobsTotal(ctx, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobsTotal", reflect.TypeOf((*MockJobAccess)(nil).GetJobsTotal), ctx, queryParams)
}

// GetTasksTotal mocks base method.
func (m *MockJobAccess) GetTasksTotal(ctx context.Context, queryParams interfaces.TasksQueryParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksTotal", ctx, queryParams)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksTotal indicates an expected call of GetTasksTotal.
func (mr *MockJobAccessMockRecorder) GetTasksTotal(ctx, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksTotal", reflect.TypeOf((*MockJobAccess)(nil).GetTasksTotal), ctx, queryParams)
}

// ListJobs mocks base method.
func (m *MockJobAccess) ListJobs(ctx context.Context, queryParams interfaces.JobsQueryParams) ([]*interfaces.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobs", ctx, queryParams)
	ret0, _ := ret[0].([]*interfaces.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockJobAccessMockRecorder) ListJobs(ctx, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockJobAccess)(nil).ListJobs), ctx, queryParams)
}

// ListTasks mocks base method.
func (m *MockJobAccess) ListTasks(ctx context.Context, queryParams interfaces.TasksQueryParams) ([]*interfaces.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", ctx, queryParams)
	ret0, _ := ret[0].([]*interfaces.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockJobAccessMockRecorder) ListTasks(ctx, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockJobAccess)(nil).ListTasks), ctx, queryParams)
}

// UpdateJobState mocks base method.
func (m *MockJobAccess) UpdateJobState(ctx context.Context, tx *sql.Tx, jobID string, stateInfo interfaces.JobStateInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobState", ctx, tx, jobID, stateInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobState indicates an expected call of UpdateJobState.
func (mr *MockJobAccessMockRecorder) UpdateJobState(ctx, tx, jobID, stateInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobState", reflect.TypeOf((*MockJobAccess)(nil).UpdateJobState), ctx, tx, jobID, stateInfo)
}

// UpdateTaskState mocks base method.
func (m *MockJobAccess) UpdateTaskState(ctx context.Context, taskID string, stateInfo interfaces.TaskStateInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskState", ctx, taskID, stateInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskState indicates an expected call of UpdateTaskState.
func (mr *MockJobAccessMockRecorder) UpdateTaskState(ctx, taskID, stateInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskState", reflect.TypeOf((*MockJobAccess)(nil).UpdateTaskState), ctx, taskID, stateInfo)
}
