// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/job_executor.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJobExecutor is a mock of JobExecutor interface.
type MockJobExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockJobExecutorMockRecorder
}

// MockJobExecutorMockRecorder is the mock recorder for MockJobExecutor.
type MockJobExecutorMockRecorder struct {
	mock *MockJobExecutor
}

// NewMockJobExecutor creates a new mock instance.
func NewMockJobExecutor(ctrl *gomock.Controller) *MockJobExecutor {
	mock := &MockJobExecutor{ctrl: ctrl}
	mock.recorder = &MockJobExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobExecutor) EXPECT() *MockJobExecutorMockRecorder {
	return m.recorder
}

// AddJob mocks base method.
func (m *MockJobExecutor) AddJob(ctx context.Context, job *interfaces.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddJob", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddJob indicates an expected call of AddJob.
func (mr *MockJobExecutorMockRecorder) AddJob(ctx, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddJob", reflect.TypeOf((*MockJobExecutor)(nil).AddJob), ctx, job)
}

// Start mocks base method.
func (m *MockJobExecutor) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockJobExecutorMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockJobExecutor)(nil).Start))
}
