// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/data_model_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataModelAccess is a mock of DataModelAccess interface.
type MockDataModelAccess struct {
	ctrl     *gomock.Controller
	recorder *MockDataModelAccessMockRecorder
}

// MockDataModelAccessMockRecorder is the mock recorder for MockDataModelAccess.
type MockDataModelAccessMockRecorder struct {
	mock *MockDataModelAccess
}

// NewMockDataModelAccess creates a new mock instance.
func NewMockDataModelAccess(ctrl *gomock.Controller) *MockDataModelAccess {
	mock := &MockDataModelAccess{ctrl: ctrl}
	mock.recorder = &MockDataModelAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataModelAccess) EXPECT() *MockDataModelAccessMockRecorder {
	return m.recorder
}

// GetMetricModelByID mocks base method.
func (m *MockDataModelAccess) GetMetricModelByID(ctx context.Context, id string) (*interfaces.MetricModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricModelByID", ctx, id)
	ret0, _ := ret[0].(*interfaces.MetricModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricModelByID indicates an expected call of GetMetricModelByID.
func (mr *MockDataModelAccessMockRecorder) GetMetricModelByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricModelByID", reflect.TypeOf((*MockDataModelAccess)(nil).GetMetricModelByID), ctx, id)
}
