// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/knowledge_network_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockKNAccess is a mock of KNAccess interface.
type MockKNAccess struct {
	ctrl     *gomock.Controller
	recorder *MockKNAccessMockRecorder
}

// MockKNAccessMockRecorder is the mock recorder for MockKNAccess.
type MockKNAccessMockRecorder struct {
	mock *MockKNAccess
}

// NewMockKNAccess creates a new mock instance.
func NewMockKNAccess(ctrl *gomock.Controller) *MockKNAccess {
	mock := &MockKNAccess{ctrl: ctrl}
	mock.recorder = &MockKNAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKNAccess) EXPECT() *MockKNAccessMockRecorder {
	return m.recorder
}

// CheckKNExistByID mocks base method.
func (m *MockKNAccess) CheckKNExistByID(ctx context.Context, knID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckKNExistByID", ctx, knID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckKNExistByID indicates an expected call of CheckKNExistByID.
func (mr *MockKNAccessMockRecorder) CheckKNExistByID(ctx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckKNExistByID", reflect.TypeOf((*MockKNAccess)(nil).CheckKNExistByID), ctx, knID)
}

// CheckKNExistByName mocks base method.
func (m *MockKNAccess) CheckKNExistByName(ctx context.Context, knName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckKNExistByName", ctx, knName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckKNExistByName indicates an expected call of CheckKNExistByName.
func (mr *MockKNAccessMockRecorder) CheckKNExistByName(ctx, knName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckKNExistByName", reflect.TypeOf((*MockKNAccess)(nil).CheckKNExistByName), ctx, knName)
}

// CreateKN mocks base method.
func (m *MockKNAccess) CreateKN(ctx context.Context, tx *sql.Tx, kn *interfaces.KN) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKN", ctx, tx, kn)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKN indicates an expected call of CreateKN.
func (mr *MockKNAccessMockRecorder) CreateKN(ctx, tx, kn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKN", reflect.TypeOf((*MockKNAccess)(nil).CreateKN), ctx, tx, kn)
}

// DeleteKN mocks base method.
func (m *MockKNAccess) DeleteKN(ctx context.Context, tx *sql.Tx, knID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKN", ctx, tx, knID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteKN indicates an expected call of DeleteKN.
func (mr *MockKNAccessMockRecorder) DeleteKN(ctx, tx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKN", reflect.TypeOf((*MockKNAccess)(nil).DeleteKN), ctx, tx, knID)
}

// GetKNByID mocks base method.
func (m *MockKNAccess) GetKNByID(ctx context.Context, knID string) (*interfaces.KN, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKNByID", ctx, knID)
	ret0, _ := ret[0].(*interfaces.KN)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKNByID indicates an expected call of GetKNByID.
func (mr *MockKNAccessMockRecorder) GetKNByID(ctx, knID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKNByID", reflect.TypeOf((*MockKNAccess)(nil).GetKNByID), ctx, knID)
}

// GetKNsTotal mocks base method.
func (m *MockKNAccess) GetKNsTotal(ctx context.Context, query interfaces.KNsQueryParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKNsTotal", ctx, query)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKNsTotal indicates an expected call of GetKNsTotal.
func (mr *MockKNAccessMockRecorder) GetKNsTotal(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKNsTotal", reflect.TypeOf((*MockKNAccess)(nil).GetKNsTotal), ctx, query)
}

// GetNeighborPathsBatch mocks base method.
func (m *MockKNAccess) GetNeighborPathsBatch(ctx context.Context, otIDs []string, direction string) (map[string][]interfaces.RelationTypePath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNeighborPathsBatch", ctx, otIDs, direction)
	ret0, _ := ret[0].(map[string][]interfaces.RelationTypePath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNeighborPathsBatch indicates an expected call of GetNeighborPathsBatch.
func (mr *MockKNAccessMockRecorder) GetNeighborPathsBatch(ctx, otIDs, direction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNeighborPathsBatch", reflect.TypeOf((*MockKNAccess)(nil).GetNeighborPathsBatch), ctx, otIDs, direction)
}

// ListKNs mocks base method.
func (m *MockKNAccess) ListKNs(ctx context.Context, query interfaces.KNsQueryParams) ([]*interfaces.KN, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKNs", ctx, query)
	ret0, _ := ret[0].([]*interfaces.KN)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKNs indicates an expected call of ListKNs.
func (mr *MockKNAccessMockRecorder) ListKNs(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKNs", reflect.TypeOf((*MockKNAccess)(nil).ListKNs), ctx, query)
}

// UpdateKN mocks base method.
func (m *MockKNAccess) UpdateKN(ctx context.Context, tx *sql.Tx, kn *interfaces.KN) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKN", ctx, tx, kn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKN indicates an expected call of UpdateKN.
func (mr *MockKNAccessMockRecorder) UpdateKN(ctx, tx, kn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKN", reflect.TypeOf((*MockKNAccess)(nil).UpdateKN), ctx, tx, kn)
}

// UpdateKNDetail mocks base method.
func (m *MockKNAccess) UpdateKNDetail(ctx context.Context, knID, detail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKNDetail", ctx, knID, detail)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKNDetail indicates an expected call of UpdateKNDetail.
func (mr *MockKNAccessMockRecorder) UpdateKNDetail(ctx, knID, detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKNDetail", reflect.TypeOf((*MockKNAccess)(nil).UpdateKNDetail), ctx, knID, detail)
}
